### ISSUE TITLE
Improve communication of whether you are playing or spectating

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#118]
I found it hard to see, at a glance, whether I was playing or spectating a game upon joining. I think this would be solved by two buttons labelled "Play" and "Watch" where clicking the appropriate button will set you to either the play or spectate state. The current state would be communicated by highlighting the appropriate button. This removes the current hard to figure out state toggle button.

**Comment by gajop** [comment]
I think it would also be good to have it visible in the status window, something akin to:
http://bit.ly/29A5qAT

Using different colors for spectate/playing and showing it clearly. Those things shouldn't be clickable, and just serve as status symbols.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/Spring-Chobby/Chobby/commit/318c2c384b5366bdea4e26919812455e5272d12d
