### ISSUE TITLE
Springsettings override

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#119]
Most springsettings should be stored in Configuration and set just before the game starts. Currently ingame fullscreen is set with this method so I know that it works. The settings tab should provide "Low", "Medium", "High" etc.. buttons which would override most of the values in Configuration. We should also set a good default. The settings can probably come from ZKL as I fixed them up a few years ago.

The Springsettings.cfg which sits next to Spring would effectively only be used for Chobby. If we later gain the ability to put springsettings in a startscript then the implementation can be changed to set the startscript.

**Comment by gajop** [comment]
This sounds like a good idea for now, and can be extended with #128

**Comment by GoogleFrog** [comment]
Needs engine. UI and gameside stuff is complete: https://github.com/Spring-Chobby/Chobby/commit/d3e281515ae38fc563d45ece9e01d638d43e9b77

**Comment by GoogleFrog** [comment]
With the ability to write to springsettings.cfg this would be reasonably easy and side-effect free to implement. This blocks it. https://github.com/spring/spring/blob/develop/rts/Lua/LuaIO.cpp#L28

**Comment by gajop** [comment]
@abma Can we somehow improve the ability and consistency of the Spring.SetConfig* functions, or get the ability to write to the springsettings file directly?

**Comment by abma** [comment]
>  https://github.com/spring/spring/blob/develop/rts/Lua/LuaIO.cpp#L28
> ... or get the ability to write to the springsettings file directly?
this change was made with the intention that no lua script shall be allowed to "escape" the spring data dirs. not sure what the exact reason is, i guess the idea was/is that lua code is written by an indivudal when engine code is written/reviewed by a lot more persons

> Can we somehow improve the ability and consistency of the Spring.SetConfig* functions

whats the issue?

**Comment by gajop** [comment]
Springsettings are in the spring data dir, and we can write to other files in the same directory.

The problem with Spring.SetConfig* is the largely inconsistent behavior. Sometimes they affect the current Spring instance, while in other times they don't, and there's no way to figure out what will work before you try it and observe.
There's also an issue what will be saved when you restart. For example, it seems to not always save the fullscreen/windowed mode stuff, and it gets overriden.

**Comment by GoogleFrog** [comment]
Thought of two more requirements:
 * Settings need to be settable for demos. They are usually not run with a startscript.
 * We need to be able to read settings after the game ends and save the changes to the settings stored in chobby_data.lua.

**Comment by GoogleFrog** [comment]
Thought of two more requirements:
 * Settings need to be settable for demos. They are usually not run with a startscript.
 * We need to be able to read settings after the game ends and save the changes to the settings stored in chobby_data.lua.

**Comment by abma** [comment]
can you give an example why you need to set settings in startscript or for demos? which setting do you want / need to change?

**Comment by abma** [comment]
> For example, it seems to not always save the fullscreen/windowed mode stuff, and it gets overriden.

it gets overwritten when the user changes fullscreen / windowed mode. imo this should be removed from the engine and moved to a widget.

**Comment by GoogleFrog** [comment]
What do you mean? Any setting may need to be changed. Clicking on the UI in chobby will be the only way users can change most of their springsettings. The settings data in the chobby UI then has to be communicated to the spring subprocess. The settings at the end of the game need to be communicated back to chobby in case the player changed a dynamic setting ingame.

**Comment by GoogleFrog** [comment]
This appears to be fixed https://github.com/Spring-Chobby/Chobby/commit/d936ed4a1de3a0ca75ab82ccc9c1fd3847f3eac0

**Comment by gajop** [comment]
Seems we got everything working with Spring.SetConfig* functions

**Comment by abma** [comment]
> What do you mean?

afaik Spring.SetConfig() doesn't work with fullscreen / window pos / window size.

**Comment by GoogleFrog** [comment]
It works if you do /fullscreen 0/1 afterwards because it seems to re-read the values.

**Comment by abma** [comment]
weird, in the "old menu" these values where overwritten / couldn't be set. so everything fine it seems!
