### ISSUE TITLE
Make a good tooltip widget

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#120]
The current tooltip widget is full of stuff we don't need and the code is quite bad. We are going to want to add custom tooltips for objects such as players and battles. A smaller, well written, tooltip widget should be written for this.

**Comment by gajop** [comment]
I was meaning to ask about this... but do you think we could make a proper widget and include it with chili, or as part of chili itself? 
I really want the ability to generate decent tooltips, and not just for this project.
I think it would be ideal if tooltip could also be a function that returns a Chili control.
