### ISSUE TITLE
Design and implement player status images

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#121]
We need to decide upon the images which should appear next to player names and implement them. This set can potentially change for different contexts.

**Comment by GoogleFrog** [comment]
My current idea is to display country and ingame-time (level) to the left of the name. If the player is a moderator we would replace the ingame-time icon with a police shield (because it is not useful to know the ingame time of a moderator). AFK and battle status would be displayed to the right of their name.

Clan would definately be displayed on the left when in a battle room. I am not sure whether to also show it in the channel list.

**Comment by gajop** [comment]
A minimalistic approach would be good, especially as a default. I like to think of the default settings as "what should we show to a user that's new to Spring". 
Thoughts:
1) Avoid clans, they are ZK-specific and more importantly, unrecognizable icons/names with almost completely useless info. I don't know why they even exist, is it planetwars or the occasional clan balance? The unrecongizability is really an issue imo, as unlike countries, ranks (which tend to either be numbers or use military ordering), clan icons have no meaning. A symbol without a meaning is bound to be confusing.
2) AFK is pretty important and useful info. I'd consider just writing it in **text** as you're currently doing, it's very clear what it means. I'm less sure on the usefulness of battlestatus. Maybe I would merge it with AFK and write it if the user isn't AFK, or add it as an option
3) The other choices seem reasonable (although positions is something I'm not considering yet), but I think it's really important to be able to configure which statuses are displayed. Country could also potentially be removed as default -> it's not something I see in most non-Spring environments.
