### ISSUE TITLE
Map choosing design

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#127]
Slightly related to #124, but still different enough to warrant a specific issue.

I think most Spring lobbies have a rather lacking UI when it comes to choosing the map, and it's something you don't really notice when playing public battlerooms with predefined map pools.

Normally when a player searches for a map, they are interested in the amount of players it supports. Either they already have the team size in mind and just want to find a map of a suitable size, or during browsing through the map list they'd like to know how many players can be played on each.

Most of the current implementations just sort the map size by dimension, but that's not adequate as the user has no idea how many players can a "8 x 8" map support. 

I think it would be best if the map can give recommended player amounts (lower and upper bound), as well as the information whether it's a team or FFA map.

**Comment by GoogleFrog** [comment]
Games should provide a list of maps available to players. This list should come with information such as player count and description. It would also be a short list and not go through VFS so the loading time of the map list would be improved.

If a user wants to see all maps they have installed then an additional button would show these maps.

**Comment by gajop** [comment]
I guess this is how games can provide map lists: https://springrts.com/wiki/Validmaps.lua , but no one seems to use this? Even the ZK implementation is disabled currently. We may need to extend that standard.

I think this sort of meta-information (game-specific player count, map type, etc.) is a bit problematic. We want new maps to also contain this meta-information and the content devs creating them definitely shouldn't need to have push rights to the game repository. Therefore, I think the map itself should contain this information too, and the games should be used for whitelist/blacklist, and *maybe* also provide duplicate meta-info so we don't have to go around adding it to all of the maps.

**Comment by gajop** [comment]
Outdated discussion.
