### ISSUE TITLE
Complete small mode implementation

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#129]
Small mode is not complete. The buttons on the left should get thinner and flatter and go down a font size. The top area should be a little smaller and My Battle ends up taking up too much space when thin.

**Comment by gajop** [comment]
Sounds good, should it also take less width? Feels too much is spent on it (in comparison to wide mode)

**Comment by gajop** [comment]
Sounds good, should it also take less width? Feels too much is spent on it (in comparison to wide mode)

**Comment by GoogleFrog** [comment]
Yes, thinner = less width.

**Comment by gajop** [comment]
Ah, right, sorry.
Another thing is I'd like tabs (chat, downloads, etc.) to be smaller than menu items, but seems that cannot be set as tier 2 menu items (skirmish, etc.) are also affected by tab size.

**Comment by GoogleFrog** [comment]
Tab panel handler should be able to take a size parameter.
