### ISSUE TITLE
Socket complaint while ingame

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#131]
* Start a multiplayer game through Chobby.
 * Exit Chobby.
 * Try to start Chobby.

Chobby does not start "bind: Only one usage of each socket address (protocol/network address/port) is normall permitted".

**Comment by gajop** [comment]
I think this is also solved with https://github.com/Spring-Chobby/Chobby/commit/1b57f82f76b79fbd6516acb210265a44ffa59fb4 . Reopen if still able to reproduce
