### ISSUE TITLE
Create proper material design skin

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#152]
We need a decent looking skin to reduce noisiness/complexity of the UI.

**Comment by GoogleFrog** [comment]
@ForbodingAngel is doing well here. An immediate todo would be:
 * Scroll bars.
 * Small panels (chat, text input, team list). I am not sure which of these need replacing.
 * Battleroom minimap. Probably just a matter of applying the panel control from the battle list.

**Comment by gajop** [comment]
Scroll bar still needs doing I guess? I tried playing it but anything I did was stupid. Clean this up or make a new issue.
