### ISSUE TITLE
Rapid Verify

### ISSUE THREAD

**Issue by ashdnazg** [Spring-Chobby/Chobby#162]
Verify - to verify the integrity of downloads. Telling users to "delete their pool/packages/whatever" is very bad.
Remove - obvious.
GC - needed by remove - to clean unused files in the pool.

**Comment by ashdnazg** [comment]
btw, I can't edit labels for some reson.

**Comment by gajop** [comment]
You cannot edit because you're not a project member.
I think these are good but should be separated into two (Verify and Remove). I don't know about GC, maybe?

**Comment by ashdnazg** [comment]
without GC, Remove can only delete the package file, and everything will still take space on your HD.

**Comment by gajop** [comment]
Separated into three issues
https://github.com/Spring-Chobby/Chobby/issues/164
https://github.com/Spring-Chobby/Chobby/issues/163

**Comment by Anarchid** [comment]
can it also make sdd's?

**Comment by ashdnazg** [comment]
that's less important (it's useful to devs, not users), but can be added I guess.
Isn't related to Chobby anyhow

**Comment by ashdnazg** [comment]
https://github.com/spring/pr-downloader/commit/4259f9cc8935f54c73b0d7360e72e848ff1b8a77
