### ISSUE TITLE
Consider SP battle persistence

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#169]
Currently MP battles are persistent but SP battles are not. If you switch to a different SP tab then the battle is recreated when you reopen the tab. There are three options:
 * Make SP battles match MP battles. Create a large status button at the top of the screen which can be clicked to navigate back to the SP battle.
 * Make SP battle state persist without the top buttons. This allows people to navigate away without breaking their configuration and is less confusing (less UI = less confusion).
 * Make SP battles recreate when the tab is opened. This is the current system.

I like option 2.

**Comment by GoogleFrog** [comment]
The "Leave" button would always give the player a new state upon reopening the tab.

**Comment by gajop** [comment]
Incidentally my order of preference is 1) consistency, 3) simplicity and 2) power users clicking less

**Comment by GoogleFrog** [comment]
So your preference is option 1 and then option 2. This is SP so I prefer simplicity to consistency with the MP screen. Consistency within the SP screen would probably be more important though.

**Comment by gajop** [comment]
My order is 1, 3 and 2 as I wrote. Basically simplicity (it being cleaned up makes it much harder for the user to break it) over power user feature (using the old state could save time)

**Comment by GoogleFrog** [comment]
Ah, 2 is not power user imo. It makes sense that if you click to a different tab and click back to your Skirmish tab then all your setup would remain unchanged.
