### ISSUE TITLE
Notifications are ugly & incorrect

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#177]
They're very hard to see as they're just text. They don't come in multiple colors (for different type of notification, such as private message VS just irrelevant chat) and their position and lack of background makes them hard to see.
http://i.imgur.com/13Cv1jC.jpg

And they're also wrong (why is My battle displaying this/any number if I'm already in that tab? it never seems to reset).

I'd still suggest implementing something like http://getbootstrap.com/components/#badges , and giving the numbers a background color that corresponds to the alertness level (success/important positive, important negative, unimportant neutral)

**Comment by GoogleFrog** [comment]
I don't know how the my battle notification is set up. Maybe someone implemented a placeholder notification for testing. In idle use I have not determined a correlation between the number and the activity.

**Comment by gajop** [comment]
It's this thing that does it: https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/gui_battle_room_window.lua#L892-L905
It could be that I wrote this code, and from what I can see it always increases the message count, and doesn't reset it when you switch/leave the battleroom or if you have the battleroom window displayed.
