### ISSUE TITLE
Some flags aren't displayed in the user list

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#180]
It might just be HK, but who knows:
http://i.imgur.com/7UAxt63.jpg

The icon obviously exists, and seems to be correct, so I'm not sure what the issue is (the long name doesn't seem to be it, as it shows my flag, while the username has a lot more chars)

**Comment by GoogleFrog** [comment]
I checked that user a few hours after this bug was reported and he had a flag in the user list. I think this is a random low priority bug. It is probably something to do with Chili.

**Comment by GoogleFrog** [comment]
I've noticed some rank images fail to display.

**Comment by GoogleFrog** [comment]
I have not seen this in a while so assume that it was fixed in some cleanup.
