### ISSUE TITLE
Use a checkbox with a slide button skin for Play/Watch states

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#189]
http://www.myfreephotoshop.com/wp-content/uploads/2013/06/4310.jpg

**Comment by GoogleFrog** [comment]
Note that a toggle button is a bad solution. It is important that users can click on one part of the UI to play and a different part to spectate. This is due to server lag and to prevent people from accidentally being in the wrong state.

**Comment by gajop** [comment]
Would it not then make sense to have buttons for joining spectators/becoming a player, next to the spectator list/team lists?
The current buttons are very confusing because they make you think there's an action ("Play" or "Watch") that would happen immediately as you clicked on it

**Comment by GoogleFrog** [comment]
I want to be able to check whether you are a spectator or a player at a glance. Seeing your state near the Start button is a bonus too.

**Comment by gajop** [comment]
Probably OK or got used to this. Let's see what new users think

**Comment by gajop** [comment]
This is fine.
