### ISSUE TITLE
Persist currently joined channels in configuration and rejoin them on login

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#19]
- The channel list should be linked to the current server and user
- See the following on how to add new config, extend the save/load and invoke it:
-- https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/chobby/components/configuration.lua#L12-L14
-- https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/chobby/components/configuration.lua#L27-L47
-- https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/chobby/components/login_window.lua#L204-L208

**Comment by TurBoss** [comment]
how i can get the list of the channels joined by the player?

or i have to store it first? if the last, howor where?

**Comment by gajop** [comment]
Check wrapper.lua from the liblobby. 
If it doesn't exist there, you should extend it.
