### ISSUE TITLE
Startboxes in SP Skirmish 

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#190]
All maps should use default startboxes.
This might require some help from people with access to the ZK infra, invoke @Anarchid 
Could at least use a dump from the site and hardcode it temporarily

**Comment by Anarchid** [comment]
Done for featured maps under zk:test: https://github.com/ZeroK-RTS/Zero-K/commit/5bc1af4ee4aa0f51ad5f2e8a275ef6a101533c14

**Comment by Anarchid** [comment]
Turns out some were missing. https://github.com/ZeroK-RTS/Zero-K/commit/5bc1af4ee4aa0f51ad5f2e8a275ef6a101533c14
