### ISSUE TITLE
Tooltip: Too long battle title wraps the font to the second line and ends up rendering over existing text

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#191]
http://i.imgur.com/kNwuMG7.jpg

**Comment by GoogleFrog** [comment]
I assume text box is not working so I left it. When text box starts working it should automatically work. See: 
 * https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/gui_tooltip.lua#L198
 * https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/gui_tooltip.lua#L377

**Comment by gajop** [comment]
Oh, well that's embarrassing

**Comment by GoogleFrog** [comment]
perhaps it is better to truncate the name with '..' instead of doing an advanced line wrap.
