### ISSUE TITLE
Autodetect battleroom type and enable only select UI elements

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#201]
This is something that's been annoying me in most existing lobbies (and Chobby is the same in this regard).
They allow you to do things which aren't valid for the current battleroom, for example:
1) Add AIs in a no-AIs-allowed room (most non-COOP rooms really)
2) Change teams in an autobalance room
3) Add/join a third team in a 1v1 room

All these things are very confusing to new players. I've watched my friend struggle to join my team (only way to play together, seeing as there's no team-play option available), and have the autohost balance him out completely randomly (as far as he can see).

It's very bad UI design to present UI actions which have no/random effect as it makes the system feel less reliable.

PS: While !forceStart allows you to run battlerooms in any weird fashion, it should probably never be done anyway and a lobby shouldn't be designed with such weird edge cases in mind.

**Comment by GoogleFrog** [comment]
I've added an issue for ZkInfra https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1126

**Comment by gajop** [comment]
possible now http://zero-k.info/Forum/Thread/22916?postID=163490#163490 ..?

**Comment by GoogleFrog** [comment]
Yes. I have already added the ability to host different types of battles. Battlerooms will need three modes:
 * Type mode - Participants are sorted into Spectators, Players and Bots. Humans can move between Spectator and Player provided there are not too many players.
 * Fixed mode - Players are sorted into teams. Teams cannot be changed. This state reflects the state of the battle in progress.
 * Custom mode - Players and bots can freely move around between teams.

Battles can move between fixed mode and the other modes.

**Comment by GoogleFrog** [comment]
The current implementation on ZKS is a bit weird. We discussed some changes and simplification. I'll implement the UI for chobby once the ZKS change are made. 

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1179
