### ISSUE TITLE
Stronger notification for votes such as !start as well as other battleroom mentions

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#202]
Currently it's just shown as an unimportant chat message, increasing the message count. There is no sound or popup like you get when a mention is received in channel chat.
There is no notification when you're being mentioned in battleroom chat like there is with channel chat.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/Spring-Chobby/Chobby/commit/aa7b356845c52e6985f02a3132803fb231692fb9
