### ISSUE TITLE
Change map by clicking on the map image

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#203]
I'd rather have this than a button actually, although I'm not exactly against an extra button, but clicking on the map image to change it seems super intuitive.

Same thing with its title (label), not entirely against it being clickable if it's going to use a bright color.

**Comment by GoogleFrog** [comment]
I dislike it when unexpected bits of the UI are secretly buttons. Something needs to highlight like a button before it is allowed to be clickable imo.

**Comment by gajop** [comment]
I think it could still highlight when it's mouse overed. Probably some other improvements are possible, I might play with how the three things (map image, title and change map button) are layout - I don't think it's optimal.

The reasoning behind this is that I think I prefer having semantically similar things near each other in the UI, rather than having all options grouped in one place. IMO, it makes for a better UX if the user doesn't have to search much

**Comment by gajop** [comment]
Might also be OK to (re)move the Change Map button now, but I didn't do it (yet).
