### ISSUE TITLE
UI should disable sending multiple logins while existing ones are being dealt with

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#204]
While connecting it shouldn't be able to spawn new login windows or click on any login-related buttons. 
Freeze those UI elements ^^

**Comment by GoogleFrog** [comment]
How do you create new login windows? I cannot.

**Comment by gajop** [comment]
I think it was chat & small mode (2nd info probably irrelevant). I clicked the "You must login to chat" and a login window popped up. I clicked login and then it started to login, but disappeared.
I could click on the same "You must login to chat" thing and a new login window would popup.

**Comment by gajop** [comment]
It's also possible to press enter multiple times in the login window
