### ISSUE TITLE
Setting presets: show which one is selected

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#206]
Assuming players are selecting the presets only for now, if one of them is selected, it should be shown as toggled.

**Comment by GoogleFrog** [comment]
Technically they can go into their _data and change the settings there. But you're probably right.

**Comment by gajop** [comment]
The proper way of doing it would be to have a "Custom" option which is highlighted when no preset is selected. This however requires you to have a system for determining what custom settings are enabled, to see whether it matches a preset or not.
