### ISSUE TITLE
Better loadingscreen images

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#207]
The ones we are using are really just temporary. They don't fit the theme and are low resolution.
PS: We don't need an egg :P

**Comment by GoogleFrog** [comment]
I think loadscreen images will be game specific.

**Comment by ForbodingAngel** [comment]
Thanks, I already have some ideas. It's on my list for what I'm doing tonight atm.

**Comment by ForbodingAngel** [comment]
Added. I think we are still up in the air with an actual logo, but what I added does look pretty nice in general.

**Comment by gajop** [comment]
I think the current one is OK. I'm not sure about the theme or logo though, but this loadscreen will work until we decide on that
