### ISSUE TITLE
No channel tab coloring (and/or counting) for normal messages

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#213]
I like it when I know that a channel has activity, even if it's not directed to me. This is no longer shown (it used to be?)

**Comment by GoogleFrog** [comment]
Tick "All chat notifies" in settings.

**Comment by gajop** [comment]
Ahh... can you make that the default? It's not very intrusive I think.

**Comment by GoogleFrog** [comment]
It is on by default. Your settings must be old.

**Comment by gajop** [comment]
Well I never unchecked it. I guess settings aren't saved in a nice way then if newly added stuff might be non-default (assuming nil == false?)
Or I could have changed it accidentally when I was testing checkboxes. In any case, nothing to do here.
