### ISSUE TITLE
Prettify download bars

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#215]
There's probably too much text in them (at least for those in battlerooms), and the colors (skin as well) could be prettier -> never invested any effort into this.

**Comment by GoogleFrog** [comment]
Half done because I removed the time estimate.

**Comment by gajop** [comment]
I heard @ForbodingAngel is/has done this? (assigned)

**Comment by ForbodingAngel** [comment]
Fixed: 
https://github.com/Spring-Chobby/Chobby/commit/ea833410fbd55d5969dfd3cd8cf97ead0c527ab2
