### ISSUE TITLE
Battlelist doesn't update hasmap/hasgame after download

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#216]
See http://imgur.com/a/YK4tv:
1) Downloaded the map in the battleroom and it updated
2) The battlelist still has old information -> Mr. Andrey is sad 

Use widget:DownloadFinished to handle this information

**Comment by GoogleFrog** [comment]
Does VFS work or do I have to do this the stupid way?

**Comment by gajop** [comment]
VFS works (see battleroom). It just needs to be refreshed each time a DownloadFinished. 
Basically like https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/gui_battle_room_window.lua#L63-L118 but for a list of maps and games, and without trying to initiate downloads for missing things

**Comment by GoogleFrog** [comment]
I had problems with inheritance.

**Comment by gajop** [comment]
Want me to do it? (Inheritance is still shit)

**Comment by GoogleFrog** [comment]
Ive got it.
