### ISSUE TITLE
Improve add AI dialog display

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#220]
Currently it has stuff like "shortName" which the user doesn't really understand. Probably having the same display as in the userlist (plus the version? not sure) would be ideal

Haven't really seen the userlist (does it have versions for Circuit and others?) in a while. Also, is it clear to the user which AIs are not real AIs (NullAI?). Two things to check also

**Comment by GoogleFrog** [comment]
If you start a skirmish game with only one team something should automatically add a nullAI to a new team. Players should never worry about fake AIs.
