### ISSUE TITLE
ZK Testing layout issues

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#227]
Quantum (not sure how to invoke) reported a few issues with the released version. All seem like things worth addressing (polish).
http://i.imgur.com/OGO0rNL.png
http://i.imgur.com/M25ap1D.png
http://i.imgur.com/wbWeC9k.png

**Comment by GoogleFrog** [comment]
I intentionally included the name overlap in the last one. If people want small mode with many channels then they can deal with overlap.

**Comment by gajop** [comment]
It's not the overlap, but rather the difference in height.
