### ISSUE TITLE
Download inconsistency

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#229]
https://dl.dropboxusercontent.com/1/view/lsudsp4pzsxabik/Apps/Pancake.io/N/Zero-k_3.jpg

**Comment by Sortale** [comment]
http://enalostka.pancakeapps.com/N/Zero-k_3.jpg

proper image link

**Comment by gajop** [comment]
I often have download reported as finished but it doesn't refresh the has_map/has_game marks in the battleroom window.
Bumping it up for next release as it's rather common and annoying.

**Comment by GoogleFrog** [comment]
Works for me, for quite a while. I probably accidentally fixed it.
