### ISSUE TITLE
Remove "has_map"/" has_game " from single player menu

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#233]
It has no meaning in the single player room. You always have maps and games. 

In general I think it would be better if instead of the label, we had an X or check mark next to the map name instead.

**Comment by GoogleFrog** [comment]
You should always have the map and game but I still want people to know that they have it. Also, something weird could happen to break this and it would be great bug report feedback from users.

**Comment by gajop** [comment]
It is wrong to design the UI based on potential bugs. This confuses new users (I had people new to Spring try the lobby and be confused with it)

**Comment by ForbodingAngel** [comment]
I agree with this in the single player room tbh. In any other situation I agree with @GoogleFrog , but I feel that @gajop makes a good point here.

$0.02
