### ISSUE TITLE
Finish modoptions panel

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#234]
Currently it reads options but provides no way of setting options.

**Comment by ForbodingAngel** [comment]
Just for the sake of mentioning it, I know sliders are sexy, but number boxes are FAR more functional. Please allow for actual value editing, even if there is a slider.

**Comment by gajop** [comment]
Have you seen how Scened does it, by combining the two controls?

**Comment by GoogleFrog** [comment]
If I do this soon the numbers are going to be sliders. We don't have the right type of editbox control for number entry.

**Comment by GoogleFrog** [comment]
Done.
