### ISSUE TITLE
Show unread messages upon switching to a channel

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#237]
When you view a chat tab with unread messages the messages which are unread should be displayed somehow. This could be via a line between the previous and the not-yet-seen messages. It could be some sort of font or colour change for the old messages.

**Comment by gajop** [comment]
Make some sort of popup when player rises up a rank. 
"Congratulations, you have achieved the rank of ..."
+ image (maybe with some animations/shaders)
