### ISSUE TITLE
Basic visiblity check for chat.

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#239]
If a chat line is invisible then it should not draw. This should fix the performance of long chat logs for all practical purposes.

**Comment by gajop** [comment]
I think it might require some redesign in the editbox/scrollpanel interaction. 
Currently we often use scrollpanels to do padding, and thus the editbox doesn't really know whether it'll be visible or not. At the same time we sometimes have an internal "offset" for single-line editboxes, making the whole thing a bit confusing. 

PS: The easy hack that will probably happen first is to check if there's an immediate scrollpanel parent.

**Comment by gajop** [comment]
basic visibility check exists now i think
