### ISSUE TITLE
Insert controls into chat

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#240]
Editboxes should have the ability to insert controls. The SetText and AddLine functions should allow you to specify a list of string Indices and controls and have the EditBox insert those controls such that it lines up with the text.

For example if a name is detected in a text line then the entry {nameStart, nameEnd, nameCombobox} would be added to the list. This combobox would act a lot like the userlist comboboxes. The same could be applied to battle names, maps and URLs.

**Comment by gajop** [comment]
It's of course doable, but I would like to design the editbox so it can be used for all applications, not just the lobby.
Do you (or anyone else) know an example of a modern editbox API in some other library I could use as reference?

**Comment by GoogleFrog** [comment]
Replaced https://github.com/Spring-Chobby/Chobby/issues/309
