### ISSUE TITLE
Start counting teams from 1 instead of 0

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#244]
I'm not surprised none of us noticed this :)

**Comment by GoogleFrog** [comment]
It is a thing which is trivial to fix but takes some design thought. It would be easy to renumber the battleroom teams so they always go from 1 to n top-to-bottom. Unfortunately other lobbies don't do this so confusion could arise if players try to take about teams by their number.

**Comment by gajop** [comment]
Right. That might be an issue, but surely we could consult with other relevant lobby devs (invoke @abma, @db81, @Licho1) and simply implement it across the ecosystem? 
I would expect everyone to agree that counting from 1 is the natural way.

**Comment by GoogleFrog** [comment]
I'm not just talking about counting from 1. If teams 1, 4 and 5 exist in the battleroom we may as well rename them to 1, 2 and 3.

**Comment by db81** [comment]
The usual use-case for that is when you have say 4 boxes and you want a team game and the opposing corners are 1 and 3.

**Comment by GoogleFrog** [comment]
Start areas should function without that pitfall.

**Comment by gajop** [comment]
This gets a lot more complicated if you try to separate team and start position (how would you even display where teams start then? draw team number on the map? - we can't display start positions yet, especially not polygons)

I'd just fix the issue as I described it initially, which should be trivial, perhaps requiring only consensus. We can try to improve this later on, but it'll require a lot more effort.

**Comment by Licho1** [comment]
I dont really care where it starts, though generally "dont fix what isnt broken" - we can just renumber in presentation and keep it if it works.. for lobbies we should switch to concept of "team slots".

**Comment by GoogleFrog** [comment]
My solution is to only change the UI end of things. Users should see teams numbered from 1 to n regardless of the underlying implementation. Ingame and lobby can be consistently implemented because the teams will have the same order in both cases.

**Comment by gajop** [comment]
Indeed, this should only be about the UI change
