### ISSUE TITLE
Implement friend support for ZKS

### ISSUE THREAD

**Issue by RafaelLinux** [Spring-Chobby/Chobby#245]
My list of friends is empty, and I think is vinculated to my ZeroK profile online, not to my lobby, so they should appear.

**Comment by gajop** [comment]
Friend list hasn't been implemented yet (in the ZK server). ZKS has no concept of friends as far as I know, and neither does the online profile.
ZKL implemented friends locally, but I'm not interested in supporting that with Chobby -> it needs proper server implementation.

**Comment by RafaelLinux** [comment]
Not really a neccesity, but a "must have". It's a pity that is not server side saved, as my profile.

**Comment by RafaelLinux** [comment]
Anyway,  I began to put my old friends like "Friends",. However,  they are appearing in"Friends" tab.  Remains empty!   :(

**Comment by RafaelLinux** [comment]
Sorry,  I mean THEY AREN'T APPEARING.

**Comment by gajop** [comment]
Maybe I wasn't clear... The feature isn't implemented, and is not going to be implemented for ZKS users until ZKS gets that ability.
Official spring server (uberserver) will get such a functionality shortly, but that too doesn't exist yet. (it has only been implemented server side and I have a WIP thing going locally)
Hope this explains things better...

**Comment by RafaelLinux** [comment]
I misinterpreted your previous answer. I'm certainly confused,  cause
WebLobby, as far as I can remember,  was saving "friends list", as ZeroK
official client for Windows (for sure). So I deduct that they're saving
that list locally.

Thank you for your explanation

**Comment by gajop** [comment]
Yes, both are only saving locally afaik. It's not a real, mutual friend system either, but more of a follower thing

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1129

**Comment by gajop** [comment]
I've renamed this issue to relate to be ZKS specific as the uberserver implementation works.

**Comment by gajop** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1129 -> liblobby implementation for ZKS can now be done

**Comment by GoogleFrog** [comment]
This isn't relevant to LuaMenu. However, I have mostly implemented friends and now we just need a UI cleanup.

**Comment by gajop** [comment]
I've extended the LuaMenu milestone slightly. Makes us look better if we support new (ZKS) features immediately as they're out.
Don't feel like I can add MM/full uberserver support though if you want to release soon.

**Comment by GoogleFrog** [comment]
I'll call this done as I can see a panel full of friends.
