### ISSUE TITLE
Chili: TextBox eats clicks by default

### ISSUE THREAD

**Issue by KingRaptor** [Spring-Chobby/Chobby#246]
The default setting in the control is `selectable = false` but it still does this.

**Comment by gajop** [comment]
I cannot reproduce this in my tests, and code is pretty straight forward...
I think this error report is incorrect. In case you still have issues, please open provide a demonstration using an example widget with instructions.

**Comment by KingRaptor** [comment]
- Copy contents of `vn/test/` from [ChiliVN repo](https://github.com/KingRaptor/ChiliVN/) to `chobby.sdd/libs/chilivn/vn/test` (overwrite or don't overwrite, shouldn't matter)
- Open `/libs/chilivn/LuaMenu/widgets`, go to line 1792 and uncomment `StartStory("test")`
- Start chobby
- When Chili VN window opens, try and fail to advance the VN by clicking on the dialogue text in the text box. (The speaker's name is a Label, so clicking it works)

**Comment by gajop** [comment]
Confirmed. This was an odd bug to fix. I'm not sure if this is a satisfying solution (perhaps screen.lua's click handling needs to be changed)
