### ISSUE TITLE
Improvement: Notify Chobby updates/upgrades

### ISSUE THREAD

**Issue by RafaelLinux** [Spring-Chobby/Chobby#251]
I was using Spring WebLobby, till it began to do strange things in my OpenSUSE linux, and there was no way to fix the problem. A great fault in that lobby was the need to check and install manually new lobby versions availability. Yes, I know it's more difficult to do this in a multi platform application, but at least it will be very usefull that Chobby warn user about a new version, like JDownloader or Telegram Desktop (both for linux) does.

;)

**Comment by gajop** [comment]
Duplicate of https://github.com/Spring-Chobby/Chobby/issues/86
