### ISSUE TITLE
Check/fix display settings for luamenu

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#254]
LuaMenu should launch in a state that agrees with the lobby display settings. When a game starts luamenu should apply the game display settings. When a game ends luamenu should revert back to the lobby display settings. Window position and size should be retained for reverting back to the lobby display settings.

The intention is to allow for a small windowed lobby that maximizes when you start the game. The default will be windowed fullscreen for both.

**Comment by GoogleFrog** [comment]
I think an engine change is required to change the window parameters directly before the game is started. Currently. a change in the code merely changes the resolution after the game loads and causes the minimap to be pixelated.

**Comment by GoogleFrog** [comment]
See https://github.com/Spring-Chobby/Chobby/commit/aa57a3e4c26e5a13d42a8e833dd7d9ce4d7f8922

**Comment by ashdnazg** [comment]
Hmm, I'll try to make it so you can use the config handler just before calling reload

**Comment by GoogleFrog** [comment]
Waiting for one frame can be implemented in chobby, but I would consider it hax.

**Comment by ashdnazg** [comment]
I think after https://github.com/spring/spring/commit/fdb02eef4eedb103856a2bc07c937e0c41ab6c7f  waiting a frame won't be necessary

**Comment by GoogleFrog** [comment]
Spring crash when changing to fullscreen windowed.
[infolog.txt](https://github.com/Spring-Chobby/Chobby/files/453151/infolog.txt)

**Comment by GoogleFrog** [comment]
The crash seems to reliably occur only when using obs to record the window.

**Comment by ashdnazg** [comment]
here too?
https://github.com/spring/spring/commit/428c95d6414171dc9d64f0c2c2a7a125e93c749f

**Comment by ashdnazg** [comment]
btw, changing the battle settings when a battle is going doesn't change the window, but changing the lobby settings does. It probably needs to check which setting is active now and which isn't

**Comment by GoogleFrog** [comment]
Fixed https://github.com/Spring-Chobby/Chobby/commit/349a6283ff3e36ab226c33b05ad2ba6e95b584a9
