### ISSUE TITLE
Ensure that luaMenu lobby syncs with ordinary lobbies

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#255]
The game started via luaMenu needs to sync with the usual launch method. This needs to be checked directly before a general test release because discrepancies with Spring.Reload could sneak in.

**Comment by ashdnazg** [comment]
I've made sure you can't read menu files from synced. Still has to be tested obviously

**Comment by GoogleFrog** [comment]
I had a desync with [tre]Pak. We were both using the same engine.

**Comment by ashdnazg** [comment]
I can't do anything without a replay (doesn't matter whose)
And most likely I will need all infologs as well.

**Comment by GoogleFrog** [comment]
I have not yet had a desync with anyone I trust to have the right versions.

**Comment by GoogleFrog** [comment]
I have a game with DeinFreund which is syncing. He either has ZKL or SWL. I am ready to say that sync is not failing in a spectacular way. The errors I had earlier were probably issues with other lobbies downloading games or engines.

**Comment by GoogleFrog** [comment]
Test game: http://zero-k.info/Battles/Detail/430271

I'm going to say this works.

**Comment by GoogleFrog** [comment]
Chobby seems to sync on the first game but may be failing on subsequent games.

**Comment by GoogleFrog** [comment]
Desync occurs and is reproducible https://github.com/Spring-Chobby/Chobby/issues/299

**Comment by GoogleFrog** [comment]
Fixed.
