### ISSUE TITLE
Hide most of luaMenu on game launch

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#256]
Most of luaMenu should be hidden when a game is launched. The most straightforward method may be to hide screen0. The better method probably involves a hide function in interfaceRoot.

There is some design to be done within this ticket. LuaMenu could draw a "view lobby" button in a corner of the screen which toggles the visibility of the lobby. In this case the background should be removed or made transparent. We can also think about ingame notifications for events such as PMs from friends.

**Comment by gajop** [comment]
I'd start by hiding screen0, and then consider specific use cases. 

We have two options for providing communication/notifications ingame:
1) Steam overlay style, where you get the lobby interface when pressing shift-tab (http://cdn.akamai.steamstatic.com/steam/store/uiupdate/Overlay.jpg)
2) LoL, WoW, chonsole style where you have it integrated as part of normal text (e.g. https://media-curse.cursecdn.com/attachments/83/772/734b7ad2d79ddaf414ce66b178d1abf6.jpg)

1) Would provide more uniformity between all games, which is good, but it might be super confusing if you have that *and* steam overlay simultaneously.

2) Cleaner, but less visually flexible solution, and it requires game-specific changes (for sending messages, such as using chonsole).

I don't think I have a clear preference for one or the other. I do want the games to be flexible enough so they can use 2)

**Comment by GoogleFrog** [comment]
Implemented, presentation could use work.
