### ISSUE TITLE
Make ZK and ZKS able to support luaMenu

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#257]
This ticket is here to be part of the milestone. ZK needs to detect luaMenu and use Reload("") instead of quit. ZKS needs to use whichever engine version is required.

**Comment by ashdnazg** [comment]
Note that ZK needs some tweaks to work with current dev-engine https://github.com/ZeroK-RTS/Zero-K/issues/1498

**Comment by GoogleFrog** [comment]
ZK basic support is done. The main remaining task there is to make the ingame UI take the menu button into account.

**Comment by GoogleFrog** [comment]
Springies seem capable of hosting dev engine. ZK still requires a stable.

**Comment by GoogleFrog** [comment]
Done.
