### ISSUE TITLE
LuaMenu-exclusive window issue

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#258]
http://i.imgur.com/5TeS46E.png

Nothing I do seems to readjust it properly. Maybe some callins aren't happening in luamenu.

I have a *similar* issue without LuaMenu, although it's not identical (it happens on /luaui reload, and can be fixed by toggling maximize).

**Comment by GoogleFrog** [comment]
Oops https://github.com/Spring-Chobby/Chobby/issues/262
