### ISSUE TITLE
Loadscreen is incorrect

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#261]
Start a local skirmish game through chobby. The loadscreen shows a chobby loadscreen, not the loadscreen of the game.
![loadscreen](https://cloud.githubusercontent.com/assets/1318249/18127298/ed75bed2-6fc2-11e6-847a-40810ea3bba7.jpg)

**Comment by GoogleFrog** [comment]
Seems to occur randomly.

**Comment by ashdnazg** [comment]
This never happened to me and doesn't make sense.
Could obviously be solved by removing the image itself from the folder (no need for a loadscreen that should be presented).
But still weird.

**Comment by ashdnazg** [comment]
Ok, I've managed to reproduce, I'll debug this

**Comment by ashdnazg** [comment]
fixed here 3a3dd1a034a5b3f0d71cedc85297bb3e0333859c
