### ISSUE TITLE
GamePreload does not call upon leaving a game

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#263]
See https://github.com/Spring-Chobby/Chobby/commit/c206b10ae472aaf5305db0feb32a84771483e213

**Comment by ashdnazg** [comment]
well, it shouldn't.
I guess I'll add some callin for after a game is unloaded

**Comment by ashdnazg** [comment]
https://github.com/spring/spring/commit/4d249756c6d9aee375a6892432eba11198c77c92

**Comment by GoogleFrog** [comment]
Ideally these would only be closed once the change is in chobby. However, the ticket could be renamed and relabeled to say that chobby now needs changing.

This ticket is still engine because ActivateMenu is not in the widget handler and we're using almost-pure basecontent.

**Comment by ashdnazg** [comment]
https://github.com/spring/spring/commit/482ab399c7d36bd0c9fd128967fe7522fc4184a6
