### ISSUE TITLE
Master cannot be merged into luaMenu

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#264]
All the files have changed locations. I recommend that master not be changed and eventually replaced.

**Comment by ashdnazg** [comment]
I've migrated the two commits missing in luamenu.
https://github.com/Spring-Chobby/Chobby/commit/41b5f0d339902cf329eb8b5936e119ec64ed33c4
https://github.com/Spring-Chobby/Chobby/commit/5b0e2f0f88c1a7c4abb5a6ccab817a53864f5cdf

**Comment by gajop** [comment]
Can we please do this now? We dont need separate branches. I'm not next to my computer ATM, but I can do it later today if there is nothing else we need from master (I haven't been following all commits closely)

**Comment by GoogleFrog** [comment]
As far as I know everything from master has been migrated. It would be good if you could do it later today.

**Comment by ashdnazg** [comment]
https://github.com/Spring-Chobby/Chobby/commit/bd4e81e6c85909d5d492540fbdd393ddd539ffd6
