### ISSUE TITLE
WindowBorderless cannot be changed on windows

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#268]
I start chobby in windowed mode and select Fullscreen Window in the settings. This should set WindowBorderless = 1 but instead it causes the top bar of the window to become thin. The window is still draggable and resizable. May also occur on Linux.

The method is Spring.SetConfigInt("WindowBorderless", 1).

**Comment by ashdnazg** [comment]
hmm, indeed.
Weird.

**Comment by ashdnazg** [comment]
Set WindowPosX and WindowPosY to 0 before that and it should work.
I prefer not to lock it in the engine.

**Comment by ashdnazg** [comment]
https://github.com/spring/spring/commit/746de9ce03a5b345faabe22d093154f415db2c7e

**Comment by GoogleFrog** [comment]
How is that used and will it make Shadowfury rage?

**Comment by GoogleFrog** [comment]
See https://github.com/Spring-Chobby/Chobby/issues/254

**Comment by ashdnazg** [comment]
I'm starting to fear we have no option here other than forcing a restart if the player wants to switch between windowed and borderless.

**Comment by GoogleFrog** [comment]
The issue is that switching between windowed an borderless should be a fairly common behaviour. I expect some people to want to use the lobby in windowed mode and have the game launch into borderless. We could force fullscreen instead of borderless in that situation however it would be annoying to do so.

**Comment by ashdnazg** [comment]
I'm aware of that, but it seems that supporting it causes all kinds of hangs crashes etc.

**Comment by ashdnazg** [comment]
I may be able to support it on windows in some way, but no idea how to do that on linux (if it's even necessary)

**Comment by ashdnazg** [comment]
should be fixed in https://github.com/spring/spring/commit/428c95d6414171dc9d64f0c2c2a7a125e93c749f
