### ISSUE TITLE
One Pixel gap between menu and edge

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#269]
There is a one pixel gap between the edge of the menu and the edge of Spring. I tried to send a chili control outside that area, with no effect. The bug could be anywhere so I'll just apply every label.

![menugap](https://cloud.githubusercontent.com/assets/1318249/18207632/48802a94-716f-11e6-9475-cb0c569982dd.jpg)

**Comment by GoogleFrog** [comment]
The gap remains after hacking chili to draw screen0 100 pixels left. So I think this is an engine bug.

**Comment by ashdnazg** [comment]
I find it highly unlikely that it's an engine bug. Did you try to draw other lua stuff there?

**Comment by GoogleFrog** [comment]
No. Also, there is a gap at the bottom of the screen.

**Comment by GoogleFrog** [comment]
Chili bug.
