### ISSUE TITLE
Spring.Reload freezes at load skirmish AI

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#273]
I am unable to start any games through chobby with 103.0.1-88-g1a9cfdd. The loading of the game always freezes at loading skirmish AI. Normal engine usage works fine.

**Comment by GoogleFrog** [comment]
This seems to be related to window recreation. Removing the window changing code, or setting both lobby and game display equal, makes Spring start fine. If I set the lobby to windowed and the game to windowed fullscreen then game loading never completes.

**Comment by GoogleFrog** [comment]
This screen is viewed forever. However the game seems to be running.
![screen00290](https://cloud.githubusercontent.com/assets/1318249/18222339/0b3a4cc8-71d8-11e6-9299-4a37abcee305.png)
`[f=-000001] Reading Estimate PathCosts [32]
[f=-000001] [LoadFinalize] finalized PFS (41ms, checksum 95867e31)
[f=-000001] Loading Skirmish AIs
[f=-000001] [WatchDog] deregistering controls for thread [load]
[f=-000001] Mex Placement Initialised with 32 spots.
[f=-000001] GameID: 323fca57295602d676bbfe8640c2d64e
[f=-000001] Connection attempt from GoogleFrog
[f=-000001]  -> Version: 103.0.1-88-g1a9cfdd develop
[f=-000001]  -> Connection established (given id 0)
[f=-000001] Skirmish AI "CAI (1)" (ID:0, Short-Name:"CAI", Version:"") took over control of team 1
[f=-000001] Player GoogleFrog finished loading and is now ingame
[f=-000001] Server, >Ping {}
[f=-000001] Server, <Ping {}
[f=-000001] Server, >Ping {}
[f=-000001] Server, <Ping {}
[f=-000001] <GoogleFrog> Allies: I choose: Engineer Trainer!
[f=-000001] Saved: screenshots/screen00290.png
[f=-000001] Server, >Ping {}
[f=-000001] Server, <Ping {}`

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/Spring-Chobby/Chobby/files/453168/infolog.txt)

**Comment by GoogleFrog** [comment]
If I set windowed -> fullscreen then the game is also visually stuck at the end of the loading screen. Tabbing out and into the game results in a completely black screen.

**Comment by ashdnazg** [comment]
should be fixed in https://github.com/spring/spring/commit/428c95d6414171dc9d64f0c2c2a7a125e93c749f
