### ISSUE TITLE
Permanent text "LuaMenu Entry Point..."

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#274]
Games started through Chobby have "LuaMenu Entry Point: "LuaMenu/main.lua"" sitting in the default engine console location.
![screen00292](https://cloud.githubusercontent.com/assets/1318249/18222543/d963a07c-71dd-11e6-9990-729601027389.jpg)

**Comment by ashdnazg** [comment]
fixed in https://github.com/spring/spring/commit/146b8d1cd99a61581d44e47fa47b25f8cd2c667e
