### ISSUE TITLE
widget:MouseMove is not in LuaMenu

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#276]

**Comment by ashdnazg** [comment]
Are you 100% certain?

**Comment by GoogleFrog** [comment]
Does MouseMove not call every time the mouse moves?

**Comment by gajop** [comment]
Only after you've clicked and returned true in MousePress I think

**Comment by ashdnazg** [comment]
^

**Comment by GoogleFrog** [comment]
Ok, so it turns out it does not do what I want it to do.

**Comment by GoogleFrog** [comment]
I've made my temporary MouseMove reimplementation into a more permanent solution.
