### ISSUE TITLE
Rejoining battle safety

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#279]
We should prevent people from rejoining the battle they are currently playing in without explicitly leaving it first. Detecting your battle is a somewhat difficult task because founders are not necessarily playing in their battle.

**Comment by ashdnazg** [comment]
won't it be best to just disallow rejoining without leaving?

**Comment by ashdnazg** [comment]
prevent misclicks and whatnot

**Comment by GoogleFrog** [comment]
Yes, there should be a confirmation to rejoin any battle while you are already in a game. I just feel like players should be warned further about rejoining a battle they are in. Perhaps the button could be greyed out.

**Comment by ashdnazg** [comment]
I think greying out a start button (with a tooltip of, "can't join while in a game") is the best approach
