### ISSUE TITLE
No game UI when launching through Chobby

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#284]
I reported this issue on Gitter. Now I reproduced it on a clean PC.
1. Download newest engine https://springrts.com/dl/buildbot/default/develop/103.0.1-96-g5ac4b4c/linux64/
2. Download newest ZK: master on https://github.com/ZeroK-RTS/Zero-K https://github.com/ZeroK-RTS/Zero-K/commit/1e1fd14ebcd016920d466ff104c359adc237447d
3. Download newest Chobby: master on https://github.com/Spring-Chobby/Chobby https://github.com/Spring-Chobby/Chobby/commit/1e42582bb8bc1b1e7c59ac500061239b9d8686df
4. In springsettings.cfg, set "Chobby $VERSION" as DefaultLuaMenu and launch Spring
5. In Chobby Settings, set Singleplayer to "Zero-K Dev"
6. Open Singleplayer tab and launch game (Titan Duel is selected with CAI as AI)
7. ??
8. No UI is displayed (http://i.imgur.com/6twIYLp.png)

Infolog: http://pastebin.com/TE62qezn

PS: It seems to me as if Chobby is also hiding game's UI.
PSS: By default the mouse gesture build system seems to be enabled still.

**Comment by GoogleFrog** [comment]
Do something more normal. Try the latest stable of both.

**Comment by GoogleFrog** [comment]
Also I have not tried 103-96. The garbage collector might be breaking everything for all I know.

**Comment by gajop** [comment]
So what's the latest stable? I'm trying to test LuaMenu here

**Comment by GoogleFrog** [comment]
The versions with VERSION.

**Comment by gajop** [comment]
I tried the three stables:
```
Zero-K v1.4.9.1
 ~/spring-static/spring_\{develop\}103.0.1-95-g20ebb8c_minimal-portable-linux64-static/spring
Chobby v0a.0.9.0
```
Doesn't seem to work

**Comment by GoogleFrog** [comment]
You should put a lot of echos in and figure out what is happening.

**Comment by gajop** [comment]
I'm taking a flight tomorrow and have a conference later on, but I will try to do that when I have the time then.

**Comment by ashdnazg** [comment]
103-96 doesn't cause this.

Did you try launching that ZK version not through Chobby?

**Comment by Anarchid** [comment]
I have experienced this issue. Same version of ZK launched through SWL works.
The UI is present "physically": it swallows clicks and causes actions if i click by muscle memory. It is just not rendered.

**Comment by gajop** [comment]
Oh.. Initial tests suggests it's engine related. Will have to try again later.

**Comment by ashdnazg** [comment]
I just can't reproduce this on my machine :S

**Comment by gajop** [comment]
It may help if you can tell me what works for you, so I can try and
reproduce that.
Might be a windows/Linux thing or something to do with unclean states
(although I think mine were clean on at least one machine I tried)

**Comment by ashdnazg** [comment]
I suspect memory error.
Any chance you could compile with address sanitizer?

**Comment by gajop** [comment]
How?

**Comment by ashdnazg** [comment]
I've found the issue, will push a fix momentarily

**Comment by ashdnazg** [comment]
https://github.com/spring/spring/commit/958b6473903d7c6f184537357d18bd3da15716f2
