### ISSUE TITLE
Downloader issues with isolation mode

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#285]
Currently the in-engine downloader appears to ignore isolation mode. Files are downloaded to the most general Spring folder. Both VFS and Spring cannot find these files (because its in isolation mode) so downloading is effectively useless in this case.

**Comment by abma** [comment]
can you test if it works please?

the change is untested, sorry.

**Comment by GoogleFrog** [comment]
Yes, probably within 24 hours.

**Comment by GoogleFrog** [comment]
With 103.0.1-106-gb7a1524 downloads no longer start in isolated mode.

**Comment by GoogleFrog** [comment]
This change also caused non-isolated mode to download files to the local directory instead of the general spring place.

**Comment by abma** [comment]
infolog.txt please

**Comment by GoogleFrog** [comment]
There is nothing interesting. 
[infolog.txt](https://github.com/Spring-Chobby/Chobby/files/465431/infolog.txt)

**Comment by GoogleFrog** [comment]
This appears to be an intermittent error. Sometimes the download works and sometimes it does not.

**Comment by abma** [comment]
can you post infolog.txt of a failed attemp then?

also the spring version we tested had a bug: https://springrts.com/mantis/view.php?id=5343

please test with the latest version.

**Comment by ashdnazg** [comment]
this bug is unrelated to downloading

**Comment by abma** [comment]
its still not clear what the bug is, i can't reproduce it.

**Comment by ashdnazg** [comment]
I meant 5343 isn't related to the downloading issue, so there shouldn't be a difference between the versions

**Comment by abma** [comment]
"should"... we ned facts! ;-)

**Comment by ashdnazg** [comment]
yes, the fact is that download dir isn't dictated by checksums.

**Comment by abma** [comment]
maybe missing checksums leads to "Sometimes the download works and sometimes it does not".

-> we still need more info + we should use the development version with fixed checksums as removes at least the warnings/error messages which are shown at start of spring.

**Comment by ashdnazg** [comment]
> maybe missing checksums leads to "Sometimes the download works and sometimes it does not".

No, the error in checksums was related to a specific function. I agree that latest version should be used when possible, but the focus should be on the actual issue at hand.

**Comment by abma** [comment]
> No, the error in checksums was related to a specific function. I agree that latest version should be used when possible, but the focus should be on the actual issue at hand.

I'm bad in ignoring error messages in infolog.txt

**Comment by GoogleFrog** [comment]
I just implemented map downloading for matchmaker queues and it has created some interesting behaviour. On my first launch of chobby the first map was downloaded to the correct folder. Some other maps were downloaded to my main spring folder and others were skipped as they already existed in my main spring folder. On subsequent launches the first map was consistently downloaded to the correct folder while subsequent maps were skipped because by this point they all existed in my main spring folder.

**Comment by abma** [comment]
try again please :-)

**Comment by abma** [comment]
side note it should now always downloads into the spring writeable dir, see infolog.txt, "Using read-write data directory..."

**Comment by GoogleFrog** [comment]
Thanks, it seems to work now.
