### ISSUE TITLE
Required engine changes

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#29]
The following are engine changes required to make a decent ingame lobby:
- [x] Spawn new engine instance instead of restarting (https://github.com/spring/spring/commit/0155b5c22ac641195fd7d26067af3995997018d6)
- [ ] Process tracking of the started Spring
- [ ] Run Spring without specifying a map
- [ ] Set springsettings temporary in a startscript
- [ ] IME handling (support IME and specify the position where the IME should appear: https://wiki.libsdl.org/Tutorials/TextInput); chili's editbox should be updated to rely on this
- [ ] Notification/application alert status (make it possible to change the application window state to alert the user to a change)

**Comment by GoogleFrog** [comment]
Engines cannot be spawned on windows. That tick doesn't count.

**Comment by gajop** [comment]
Updated list, can confirm engine works on Windows now too

**Comment by gajop** [comment]
Since it seems that engine work will require a considerable amount of time I'm splitting these into separate issues that can be seen https://github.com/Spring-Chobby/Chobby/issues?q=is%3Aissue+is%3Aopen+label%3AEngine
