### ISSUE TITLE
Unreliable connection status detection

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#292]
The connection status that's written in the top right is unreliable.
I've been disconnected for a few minutes, reading the chat log, and it still had me as "Online".
I got my connection back again, and the automatic reconnection started. My status then changed to "Connecting..." but stayed like that for far too long, even though it appeared as I reconnected fine (I could see chat).

**Comment by GoogleFrog** [comment]
Fixed by https://github.com/Spring-Chobby/Chobby/commit/66f2e5cb50c3293900ecb7531df99aa047e76869
