### ISSUE TITLE
Chobby does not respond to site-> lobby commands

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#296]
Those commands include stuff like:
- picking map on website
- picking mission on website
- joining planet/battle on website

Part of it can be moved to server protocol (changing map) but other things are in client's power - like starting a mission selected from website.

**Comment by GoogleFrog** [comment]
I've done all I can do. https://github.com/Spring-Chobby/Chobby/commit/7e191899e1dfc3604abb100e01d7a475651db6aa

Chobby seems to respond to site -> lobby commands. More can be added if a set of requirements is well defined. I cannot see how to do things which are not relevant to the current situation.

**Comment by Licho1** [comment]
ok if we need more we should probably make it use some proper json object format instead of silly "url" parsing.
