### ISSUE TITLE
It is not possible to play using spring engine AI if you have game with lua AIs

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#297]
Option should exist for those hardcore SP gamers.
We could whitelist them or something.

**Comment by GoogleFrog** [comment]
I blacklisted the default spring engine AI because none of them work for ZK (this is a per-game config blacklist). If you have Circuit or the graph AI they should show up.

https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/configs/gameConfig/zk/aiBlacklist.lua
