### ISSUE TITLE
Every Spring.Reload after the first causes desync

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#299]
Spring instantly desyncs if you join a game after already loading a game. It seems that the game can even be a singleplayer game, the determining factor appears to be whether Spring.Reload has been called. This is the good type of desync, no units move and desync messages appear instantly. Its probably just some leftover state.

**Comment by GoogleFrog** [comment]
Mantised https://springrts.com/mantis/view.php?id=5349

**Comment by ashdnazg** [comment]
Should be fixed after https://github.com/spring/spring/commit/98e397983e676b8df7baeff1a71f03d16013bcd4
