### ISSUE TITLE
Connection lost while loading

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#302]
Currently loading disconnects you from the server. This implies that widget:Update is not being called. It would be nice to call this as often as required to stay connected to the server.

**Comment by abma** [comment]
https://github.com/spring/spring/commit/39fe5c33cd1701d731f281c468bce1a72c0cbc0f

**Comment by Licho1** [comment]
Also we could maybe drop the silly ping stuff from protocol.

**Comment by ashdnazg** [comment]
O.o

**Comment by Licho1** [comment]
There should be a socket disconnect in most cases.  If there is not, then the first time server attempts to send something to client (which atm would be max 30s until next matchmakerstatus) it will detect socket has been disconnected.

**Comment by abma** [comment]
there were several discussions about having a ping or not in the spring lobby protocol. Removing the ping would lead to ghost clients inside a battleroom: thats why it was added.

The conclusion for the spring Lobby Protocol was that its better to have it. IMHO: Battlerooms are not for idleing like in irc. When a player clicks "ready" all technical things around should be ready (which includes the network connection), too. One ghost player annoys all other players.

Without sending data over a socket a disconnection is not detected. For a reliable detection both sides need to check for ping/data send.

**Comment by GoogleFrog** [comment]
The next task is to put that engine on the ZKS and test it.

**Comment by GoogleFrog** [comment]
I've connected to a few games with 131 and it seems to work correctly.
