### ISSUE TITLE
Cannot download Chobby using pr-downloader on Linux

### ISSUE THREAD

**Issue by lagerspetz** [Spring-Chobby/Chobby#304]
On my Linux Mint 18 64-bit desktop,
I downloaded the latest Spring static ( https://springrts.com/dl/buildbot/default/develop/103.0.1-127-g9f68416/linux64/ ) as it seems to include pr-downloader, as instructed from here:
https://springrts.com/wiki/Pr-downloader
I then tried to download Chobby repeatedly, but got:
```
~/D/spring103-for-chobby> bin/pr-downloader chobby:test "Blank v1"
pr-downloader 0.7-334-g3a4f9f6
[Info] Using filesystem-writepath: /home/lagerspe/.spring
[Info] Found 25 repos in /home/lagerspe/.spring/rapid/repos.springrts.com/repos.gz

[Info] md5 correct: cf90efce56d40c5dcbf475ae14e1cd29
[Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:530:download(): Failed to setup download 0/1
[Info] Download complete!
```

Chobby does not show up in Spring 103's game menu, my system Spring's game menu, or Spring v. 100.0's game menu (at .spring/engine/100.0, left over from previous Zero-K Lobby install).

**Comment by GoogleFrog** [comment]
Chobby is not a game, it is a lua menu. You can probably run it with command line arguments. I use DefaultLuaMenu = Chobby $VERSION in springsettings.cfg to run the git version. I don't intend for raw pr-downloader to be a supported method of running Chobby. It should always have some sort of wrapper or self update capability.

**Comment by GoogleFrog** [comment]
I think my short answer is "don't get Chobby with pr-downloader". If you are hardcore enough to want to test the development versions just clone the repository and put "DefaultLuaMenu = Chobby $VERSION" in springsettings. If you are not that hardcore then wait for releases with a better auto-update ability.

**Comment by lagerspetz** [comment]
I think the README should say to use chobby.exe to launch chobby, as mentioned by Licho here:
http://zero-k.info/Forum/Thread/22781?Search=&User=&grorder=&grdesc=False&grpage=2

> You can launch chobby using this wrapper, it auto gets proper engine and updates chobby, this should fix your issue.
> 
> http://zero-k.info/lobby/chobby.exe
> 
> (works on linux using mono chobby.exe ,you might need to chmod u+x spring until next version is released tommorow). 
Currently the README states:

> Chobby, the ingame lobby.
> Installation
> 
> Chobby is on rapid, under the "chobby" tag. The development version can be obtained directly from here.
> 
> To download with pr-downloader use this command line:
> 
> pr-downloader chobby:test "Blank v1"
> 
> Launching
> 
> You can launch Chobby from spring start menu like any other game. 
All of this is incorrect according to you.

**Comment by gajop** [comment]
1) This should work: `pr-downloader chobby:test`. Maybe you have some very old engine.
2) README is now updated.

Hopefully things should be clear now. If you have any specifics you can create a new issue.

**Comment by Licho1** [comment]
it also failed for me i had to use pr-downloader -rapid-download chobby:test or something like that (specify that its a rapid)
