### ISSUE TITLE
Spectating MP submenu tab

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#308]
There should be a submenu tab which lets you spectate games. This will display games similarly to the Server List. Clicking on the games will spectate them instead of joining the room. Matchmaker rooms should be displayed in this list.

**Comment by Licho1** [comment]
This seems to be not very useful, because you can spectate any game from the multiplayer list already.

**Comment by GoogleFrog** [comment]
That ability creates a confusing UI and causes you to leave your current battle. Joining a battleroom should be for those that wish to play next game or spectate a string of games. If you just want to watch a game without following the room (perhaps you are in MM) then you should just click spectate on a battle, not join it.
