### ISSUE TITLE
Add matchmaker stats

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#314]
ZKS now sends out MM stats. These should be added to the MM window.

**Comment by Licho1** [comment]
As per suggestion, im going to add min and max elo in queue and flag "can start instantly" if game can be started asap if palyer joins
This should incentivize 1v1 .. if we make mm stats prominent, it could glow the button if it can start instantly.
I would even consider having MM stats always visible somewhere.
