### ISSUE TITLE
Chobby can reconnect without issuing login message

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#316]
See logs here https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1259

**Comment by GoogleFrog** [comment]
What does "issuing login message" mean?

**Comment by Licho1** [comment]
According to log, chobby was disconnected from server and reconnected. Gui apparently didn't react properly and chobby didn't send "Login" message to server after socket has been reconnected.

**Comment by GoogleFrog** [comment]
Is there a specification of the protocol regarding connecting? None of it was written with reference to any documentation. It was just implemented until it started mostly working.

**Comment by Licho1** [comment]
After you connect (socket) you need to send Login (within 30s).
That's all there is.
If you don't send login, server wont know your account name and won't let you do anything (socket was in that state when you sent status to AFK)
