### ISSUE TITLE
Redesign login window

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#318]
The login window is confusing:
- It give people the option to set server and port. This option requires knowledge in order to touch it correctly so should not be present.
- It is not clear that the login UI also allows people to register. Registration should be done in a popup window that appears when you click register.

**Comment by Licho1** [comment]
Server options can be hidden in some config (presets) but i think that generally we dont need people to be able to pick any server (those who want can edit configs).
Consider adding test server as an option ,but it has to be clearly marked and not remembered.
