### ISSUE TITLE
Think about font sizes

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#321]
Font sizes need some thought put into them. In particular the chat font size is much smaller than the chat font in ZKL so the chobby chat may be annoying to use.

http://i.imgur.com/AJ2DxVR.jpg

**Comment by Licho1** [comment]
Research suggests that the bigger the better. Something about small things being taxing and annoying, making it feel hostile.

**Comment by dvr333** [comment]
I wouldn't mind an increase in font size, though the font used is quite sharp, but the bigger issue I find is line spacing. Right now character spacing within lines is so close to spacing between lines that the chat log often looks like a grid of text. Probably a couple extra pixels of space on each line would solve that.

**Comment by GoogleFrog** [comment]
I've added an option to change font size and increased it to 16 by default. We can test it out and try to find a good default. Note that nothing else in the UI has a size of 16 and that the next smallest size which occurs elsewhere on the UI is 18.

https://github.com/Spring-Chobby/Chobby/commit/fe2db7db10a6e1a2e3d25c4b5fcc4ab30a0553da

**Comment by GoogleFrog** [comment]
Font size 18 as the default seems to work well.
