### ISSUE TITLE
When you access choby from menu inside a running game, don't show BG picture

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#324]
If you access menu from running game, both static picture and the running game can be seen below chobby windows.
Show just running game under such circumstances.

**Comment by GoogleFrog** [comment]
So you're saying that the partial transparency of the menu background when viewing chobby over a running game should be increased to full transparency? I disagree because the UI could become hard to read. However the transparency can probably be increased.

**Comment by Licho1** [comment]
No, I am saying don't show BG image with giant robot AND game together. 
When game is running, swap BG image of giant robot with something of uniform color.
When not there can be a giant robot.

**Comment by GoogleFrog** [comment]
Ah I see. Would it still be semi-transparent?

**Comment by Licho1** [comment]
Yes it should be ensured that chobby is readable (even if it can be slightly more transparent). It just shoudln't combine two background images together, it looks confusing.
