### ISSUE TITLE
Battle room - gui elements overlap (ADD AI + spectators)

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#326]
http://i.imgur.com/4PinxLK.png

It is also hard to tell what is a button and what is a label.

**Comment by GoogleFrog** [comment]
Huh, that must be a bug related to making the battle room window react to !type. The Spectators area is thin because add AI and join make no sense.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/Spring-Chobby/Chobby/commit/07b34ef502a7637e4cc54379c3ff0506b9e43c73
