### ISSUE TITLE
Open channel can overlap with self info

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#331]
http://i.imgur.com/claCzVB.jpg

**Comment by GoogleFrog** [comment]
The channel tabs can overlap too. I decided that if you are enough of a poweruser to be using small mode with 8 channels then you can deal with a bit of overlap.

**Comment by Licho1** [comment]
ok. We should limit channels perhaps don't even join #zk by default (or make it gray and only join when clicked). 
Channels that are autojoined should be reviewed.

**Comment by GoogleFrog** [comment]
Ok, so I'll say the overlap is not a problem.
