### ISSUE TITLE
If battle offer from nagger is accepted, after it ends chobby thinks you are in game

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#332]
What I think happened:
1) i was in my own game (not running)
2) clicked accept on nagger
3) left the game

Now when I trie to leave MP section, it thinks I'm in a game:

http://i.imgur.com/bxtHJrN.png

**Comment by GoogleFrog** [comment]
You are probably in a hidden MM room and the "are you sure you want to leave" popup is failing to detect that the room you are in is a MM room.

**Comment by Licho1** [comment]
Then it should be closed by infra changes.

**Comment by GoogleFrog** [comment]
To clarify, chobby always thinks you are in a battle if you are in a matchMaker battle. The trick I use is to add checks to most parts of the UI to ignore battles if they have isMatchMaker. It appears that this confirmation popup does not take that into account.
