### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#335]
I had an access violation after launching a SP game, leaving the game and then launching it again. Perhaps I did not leave the game before launching again, I cannot recall.

[infolog.txt](https://github.com/Spring-Chobby/Chobby/files/493081/infolog.txt)

**Comment by ashdnazg** [comment]
Should be fixed in https://github.com/spring/spring/commit/819e5b4bdda8be95b826c0eb930d39bf661e50b5
Note that gui_chili_lobby.lua needs to use ActivateGame instead of GamePreload

**Comment by ashdnazg** [comment]
btw, only setting ingame status in OnBattleAboutToStart may be an issue since LuaMenu can start directly in a game (e.g. when spring is run with a script and a menu is specified).

**Comment by Lasica** [comment]
I had access violation bug, posted issue, probably a copy of this one:
https://github.com/Spring-Chobby/Chobby/issues/356

**Comment by gajop** [comment]
old engine, won't fix
