### ISSUE TITLE
Some GUI elements have really poor visibility

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#339]
Unchecked checkboxes are basically invisible on my setup
Button borders are not visible, text is though.

https://goo.gl/photos/ig9ytT6qwb6pACvv7

**Comment by GoogleFrog** [comment]
Your setup is a dusty screen with Venetian blind lighting. I don't think that setup needs supporting.

**Comment by gajop** [comment]
"Dusty setups aren't supported" :D
