### ISSUE TITLE
Lobby does not respond to room changes

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#342]
Tried !maxplayers and !title ..
no response
http://i.imgur.com/Jij26T9.jpg

**Comment by GoogleFrog** [comment]
Is there a list of the things which can change?

**Comment by Licho1** [comment]
Any of this can change in theory:
    public class BattleHeader
    {
        public int? BattleID;
        public string Engine;
        public string Founder;
        public string Game;
        public bool? IsRunning;
        public string Map;
        public int? MaxPlayers;
        public AutohostMode? Mode;
        public string Password;
        public DateTime? RunningSince;
        public int? SpectatorCount;
        public string Title;
        public bool? IsMatchMaker;
    }

(Of course battleid cannot, founder and ismatchmaker does not change atm in practice)
