### ISSUE TITLE
Nightwatch pm are displayed in little popup

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#344]
Nightwatch  can send useful info that should appear in the PM and not as a little popup.
For example !names
Popup is too short to display everything.

All springies are also "Nightwatch" now so whatever autohost has to pm you would be cut.

**Comment by GoogleFrog** [comment]
The little popup appears when you are sent a PM. There is a chat tab called "@Nightw.." which contains the message.
