### ISSUE TITLE
Incorrect login UI behaviours

### ISSUE THREAD

**Issue by KingRaptor** [Spring-Chobby/Chobby#349]
- When logging in with an existing username but the wrong password it says "Name not registered"
- When logging in successfully, then logging out and doing a failed login, the chat window still appears 

[Screenshot](http://i.imgur.com/4wOOwvl.jpg)

**Comment by GoogleFrog** [comment]
Where is the enum which would tell us what those response codes mean?

**Comment by Licho1** [comment]
Any specific reason you are playing dumb @GoogleFrog  ?

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/8cef0d97619bf93f992110a2baa29284a14a0d6f/Shared/LobbyClient/Protocol/Messages.cs#L126

**Comment by GoogleFrog** [comment]
That is the only file I can find and I didn't expect an inline enum.

**Comment by Licho1** [comment]
You wan't enum's being sent as strings?

**Comment by Licho1** [comment]
There is search, if the messages.cs uses enum, it's a named one and you can search it for implementation.. Or you can open it in VS and ctrl+click it if you don't want to use github search.
