### ISSUE TITLE
Server address is saved into luaui/widgets/IGL.lua, constant in sources ignored

### ISSUE THREAD

**Issue by Licho1** [Spring-Chobby/Chobby#352]
This means if we change default server, it wont be applied.
Server address from sources should be used.

Also its needed to do crazy local tests like this

http://i.imgur.com/jLrKWXn.jpg

**Comment by GoogleFrog** [comment]
I did this because it is always easier to change your IGL.lua than to change sources. If we were changing the server for players then the sources would be made to override their local settings.

**Comment by Licho1** [comment]
It could just not be saved instead (and only use local address if it exists on client) but ok..
