### ISSUE TITLE
Chobby leave player without map as active player instead of spectate them.

### ISSUE THREAD

**Issue by Sortale** [Spring-Chobby/Chobby#355]
Chobby leave me as an active player when I don't have the map when game started. I can rejoin after I downloaded but there are cases when players couldn't download the map until too late. I suspect same problem in zkl but Licho said it's Chobby only.

Licho believe this is low priority issue because Steam players should have most if not all maps already.

Reported here as suggested by Licho

**Comment by Licho1** [comment]
The problem is it starts without having map instead of waiting for dl to finish and then starting.

**Comment by GoogleFrog** [comment]
What is an active player? Chobby does not start a game if you lack the map.

**Comment by Licho1** [comment]
It should wait for DL to finish and then start. Game expects it too  (thats why there is 90s in-game wait).
