### ISSUE TITLE
Downloading maps broken -- chobby

### ISSUE THREAD

**Issue by Lasica** [Spring-Chobby/Chobby#357]
For some reason, it started to fail to download every map. 
I haven't been turning off computer and the situation was like: yesterday it worked, tomorrow it does not. It could have downloaded some patches, I'm not sure.
I've checked I'm not missing space on disk. It just stopped working overnight.

I've checked infolog but there's nothing interesting on this subject so it's useless (and I won't post it)

Not sure which version is it, I guess it's the newest but can't find version anywhere. I guess it could be a separate feature request to add "About" info.
@edit: debug mode shows version "Chobby git", not very helpful.

**Comment by GoogleFrog** [comment]
I was able to download this map http://zero-k.info/Maps/Detail/7099

**Comment by Lasica** [comment]
Out of sudden it started working days later as it stopped. I guess it's not an issue with chobby but dl server.

**Comment by Licho1** [comment]
There has been intermitten failure of infrastructure used by pr-downloader afaik.
Only way around this would be to ask wrapper for downloads, either way it's not directly a chobby issue.

**Comment by gajop** [comment]
Closing since not related to Chobby but infra
