### ISSUE TITLE
Matchmaker and Server List interface feedback

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#375]
The Play tab currently does not make it clear enough that its a matchmaker. The game can look empty with 0 players on both queues while there are many games going on in the server list.

The main suggestion was to increase the play tab to have a matchmaking section and a "hot server list games" section. The server list games would give the player the option to join one or two of the active server games in case the matchmaker is empty or near empty. I'd implement this option to smoothly disappear if MM numbers increase.

"even clicking server list is not intuitive, took me a while to realize double sword means ingame etc maybe when a game is 'open' it should have a green border or something"

**Comment by Licho1** [comment]
I would just make a "mm infobox" on top clickable from anywhere and at anytime. Details about queues can be in a "popup"

**Comment by gajop** [comment]
I don't think you need anymore feedback at this point.
