### ISSUE TITLE
Lua callout for loading save games

### ISSUE THREAD

**Issue by KingRaptor** [Spring-Chobby/Chobby#394]
Chobby now has [a widget](https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/widgets/gui_loadgame.lua) to load save games created with `/luasave` (and ZK has a widget for both saving and loading). But it doesn't actually do anything because it lacks a Spring API callout to actually load the .slsf file Spring creates for the save game. 

If the needed function already exists it should be identified for use in the widgets; else I would like for it to be added to the engine.

**Comment by ashdnazg** [comment]
no it doesn't.
reload with a script containing saveFile=blabla similar to
https://github.com/Spring-Chobby/Chobby/blob/577e3d7dd12366621667a6fd9b6ab056d569673d/libs/liblobby/lobby/interface_skirmish.lua#L155

**Comment by KingRaptor** [comment]
Works, thanks!
