### ISSUE TITLE
Wrong player count

### ISSUE THREAD

**Issue by DeinFreund** [Spring-Chobby/Chobby#407]
![img](https://i.imgur.com/Ok5Rrwf.png)

I created this room and OGS joined, the counter is still showing one.

**Comment by gajop** [comment]
I wonder, is your test actually using the latest commit from this repository? (https://github.com/Spring-Chobby/Chobby/commit/b9cb99fd4a2e69aa4636e2b005f34fc99a7b55eb)
I might've already fixed this issue (although I was fixing a bug with uber).

**Comment by DeinFreund** [comment]
I'm using the zk stable version, so possibly this is fixed.

**Comment by gajop** [comment]
Definitely fixed for ZK. Maybe broken on uber but that's a separate issue imo

**Comment by DeinFreund** [comment]
Definitely not fixed for ZK:
![notifxed](https://i.imgur.com/BdIK9Nd.png)

I joined a room, it increased the player count, then quit again and it didn't decrease even after waiting 15 minutes. Maybe zkls doesn't send an update?

**Comment by DeinFreund** [comment]
I am using the current zk stable.

**Comment by gajop** [comment]
seems OK to me now
