### ISSUE TITLE
Differentiate between Spectators and Players in Battle Preview Tooltip

### ISSUE THREAD

**Issue by DeinFreund** [Spring-Chobby/Chobby#411]
![tooltip](https://i.imgur.com/BWCtp1B.png)

I don't know who's playing and who's just watching.

**Comment by Licho1** [comment]
Client's dont know this.

**Comment by DeinFreund** [comment]
Indeed, so send it to them.

**Comment by Licho1** [comment]
Waste of data, there were already scaling issues. We do not even send all people for all battles. You only know people that you see.. and you won't see all.
