### ISSUE TITLE
Battle panel gets cut off on one panel mode

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#417]
As seen here:
https://i.imgur.com/FhMwSPi.png

**Comment by gajop** [comment]
I can replicate this by being in a battleroom and going to Settings and choosing *Split Panel Mode*: *Always One*. 
Hopefully @GoogleFrog  can review this, as it is his code originally, the relevant line is the addition of UpdateStatusAndInvitesHolderPosition() in externalFunctions.SetPanelDisplayMode
