### ISSUE TITLE
[Evo] Adv Options menu: Chobby doesn't handle large modoption categories well

### ISSUE THREAD

**Issue by Teteros** [Spring-Chobby/Chobby#419]
![image](https://cloud.githubusercontent.com/assets/5067989/26762293/990e0b0c-4937-11e7-850f-c818ce56cb41.png)

**Comment by ForbodingAngel** [comment]
I think it's more so that there are more categories than tab's it can properly display., but yes, a huge issue considering the amount of configuration that gets change in evo from game to game.
