### ISSUE TITLE
do not override WindowPos in springsettings.cfg

### ISSUE THREAD

**Issue by Jamanno** [Spring-Chobby/Chobby#424]
When I manually set 

WindowPosX = 1920
WindowPosY = 0

chobby starts fine with:
spring   --menu 'rapid://zkmenu:stable' --config ~/.config/spring/springsettings.cfg

But soon when I start a game in chobby it puts me back on my first screen and resets my WindowPosX to 0.
Maybe as workaround add a option to manually choose windowPosX?

**Comment by Licho1** [comment]
You should probably set this in chobby settings and not springsettings (in its config files)

**Comment by Jamanno** [comment]
Where? Is there a seperate config file for chobby which is not overwritten when using pr-downloader zkmenu:stable?

**Comment by Licho1** [comment]
It probably does not have WindowPosX yet, just saying it does overwrite springsettings.cfg based on its own chobby configs.

**Comment by gajop** [comment]
Just to clarify, this setting is not overwritten with `pr-downloader zkmenu:stable`, but rather the position is set within chobby code itself, e.g. https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/widgets/gui_settings_window.lua#L160-L161

I think there is no intention to support things like arbitrary WindowPosX/Y but it seems that in your case you are trying to force Chobby to display on the second monitor, which is a lot more reasonable request.

**Comment by GoogleFrog** [comment]
Fixed here: https://github.com/ZeroK-RTS/Chobby/issues/268
