### ISSUE TITLE
Chobby crashes when pressing the ¨ ! ] key (left upper key relativ to enter) twice on linux

### ISSUE THREAD

**Issue by CoppaMan** [Spring-Chobby/Chobby#427]
When I tried to find the key for drawing on the map I pressed this key twice within a second which led to a crash of chobby and the spring engine. This will put down one ¨ character on my keyboard with swiss german layout and keymap. 

Reproducing the crash in a terminal gave me the following error message:

`chobby.exe Information: 0 : Chobby closed connection`
`chobby.exe Warning: 0 : Spring exit code is: 139, assuming crash`

**Comment by gajop** [comment]
Can you post the full infolog?

**Comment by CoppaMan** [comment]
Content of the log/20170713060050_infolog.txt:
https://pastebin.com/sPdURuLi

**Comment by gajop** [comment]
That doesn't seem to be it, notice how there's no crash.
If you're using Chobby with ZK's wrapper, there should be an infolog_full file I think.
Alternatively, can you find yourself here: https://github.com/ZeroK-RTS/CrashReports/issues ?

**Comment by CoppaMan** [comment]
Ok, I'm using the ZK fork of the wrapper, so there was an infolog_full:
https://pastebin.com/US66QvqT

**Comment by gajop** [comment]
That output is clearly not related to your issue.

**Comment by CoppaMan** [comment]
I deleted the infolog_full and the crash did not recreate it. No other application is troubled by this key combination so far. I will retry this on a different install but this will not happen within a week or so.

**Comment by gajop** [comment]
How come your log isn't being reported here: https://github.com/ZeroK-RTS/CrashReports/issues ?
Normally the wrapper should ask you if you want to upload your log.

**Comment by CoppaMan** [comment]
It's just silently crashing, no pop ups or onscreen messages are happening. Like I said, the only feedback I get is by starting it in a terminal and let it crash where it points to the spring exit code 139

**Comment by CoppaMan** [comment]
Ok, optirun is part of the problem. I normally run chobby.exe with:
`optirun mono path/chobby.exe`
Running it on the internal GPU fixes the problem.

**Comment by gajop** [comment]
I understand this means the issue is not with chobby or the wrapper.
Reopen and elaborate if I'm wrong.

**Comment by CoppaMan** [comment]
Or just add notice somewhere to use primusrun instead of optirun to start chobby with a dedicated GPU when they are using bumblebee. But thank you for your time.

**Comment by gajop** [comment]
I just run `mono chobby.exe` directly on Ubuntu and I don't understand what any of the above does, so I don't think I can write the instructions. 
If you think you can, please write them and send a PR.

Realistically this is something that's also worth adding to the ZK site, here: http://zero-k.info/Wiki/Download

**Comment by CoppaMan** [comment]
Bumblebee is a nvidia driver that allows to switch between an intel gpu and a nvidia gpu and is concerning laptop users only who want to save battery life when they don't need the extra graphics power of their nvidia gpus. Optirun and Primusrun enables the dedicated gpu for the command behind it.
Im going to PM a dev and ask if this has already been brought to their attention.

**Comment by gajop** [comment]
What I'm saying is that it's best if the instructions are written by someone familiar with the software.

**Comment by Anarchid** [comment]
I was using bumblebee 2011-2016. RIP

It is now unsupported afaict and nvidia drivers offer native support.

Currently i run the whole desktop on dedicated gpu (i tested and this was faster for me, bb has very expensive screencopying it seems). The one real downside is power consumption but then i don't really play zk unplugged.

**Comment by CoppaMan** [comment]
What does the nvidia drivers offer native support for, their gpu switching tech?
I only use a window manager like Gnome when I'm plugged in anyway and a light weight tiling wm when commuting by train. So i wouldn't mind if only my entire Gnome session runs on the dedicated gpu.

**Comment by Anarchid** [comment]
The proprietary Nvidia drivers for Linux now natively support switching modes, as well as running the DE on the discrete GPU. Search first for RandR. IIRC there are some CLI commands you can invoke to switch the GPU (but not like bumblebee last time i checked). This may have progressed since as i haven't bothered using my intel gpu for two years now.

**Comment by Anarchid** [comment]
Quick google suggests that there's also a new option now called `nvidia-xrun`. But that may or may require a whole different X session.

**Comment by CoppaMan** [comment]
I will look into these and see how well they work on arch. If there are enough laptop linux players, this could be relevant info for the Zero K docs. Does the lobby run any kind of statistics on gpu models used?
