### ISSUE TITLE
[Uber] Map display and battle list doesn't update on map change

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#433]
![image](https://user-images.githubusercontent.com/369586/33360556-03367316-d489-11e7-8064-28dea682d9ea.png)

![image](https://user-images.githubusercontent.com/369586/33360564-0f7e102a-d489-11e7-8357-16fc9a5c2ad5.png)

Additionally battle list does not update either

![image](https://user-images.githubusercontent.com/369586/33360579-23d87d76-d489-11e7-82a6-876e1f97f1a9.png)

**Comment by ForbodingAngel** [comment]
Login and logout causes battle list to update

**Comment by gajop** [comment]
fixed with https://github.com/Spring-Chobby/Chobby/commit/37eb9adfc0bf94996397aaa1b9bee6fef2c0a3ab
