### ISSUE TITLE
[Uber] AIs are added as spectators and other related issues

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#434]
I can't add a chicken ai, here is the log:
https://pastebin.com/QcUkucL1

![image](https://user-images.githubusercontent.com/369586/33360951-e50401a4-d48a-11e7-8678-9ee13430396b.png)
As you can see in this image, there is me on one team and shard on the other, but the server reports that there aren't enough teams (min on the server is 2).

I load it up in weblobby and this is what I see has actually happened:
![image](https://user-images.githubusercontent.com/369586/33360986-0460226c-d48b-11e7-8dce-6a87c98a52f0.png)

I'll append issues to this as I find them.

**Comment by gajop** [comment]
Fixed with https://github.com/Spring-Chobby/Chobby/commit/ee87060c71c9361bce377a2de1bab82e719d819f

Make new issues for new bugs ^^
