### ISSUE TITLE
Request to merge Music branch

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#438]
https://github.com/Spring-Chobby/Chobby/commit/fcc016aa0f8618bc00b243150b0c24ea91c76837

This branch has the ZK specific menu music removed and replaces it with a menu track written by Wasp for that specific purpose for the spring community. This is a far better choice to be generically distributed with chobby.

In the future, there should be a larger conversation about game specific lobby music, but this is an important first step.

**Comment by Anarchid** [comment]
This pull request is not a pull request?

**Comment by ForbodingAngel** [comment]
I have commit access. Working from a fork isn't a lot of fun especially since then I have to clone the repo multiple times. Throwing it in a branch was a nice and easy compromise.

**Comment by gajop** [comment]
You can still make a PR from one branch to another, in the same repo.

**Comment by ForbodingAngel** [comment]
Oh that's neat. Didn't know that.
https://github.com/Spring-Chobby/Chobby/pull/442

**Comment by gajop** [comment]
OK, closing this then. You can assign people and comment there if you want.
