### ISSUE TITLE
Downloads are not working with newer engine versions

### ISSUE THREAD

**Issue by azaremoth** [Spring-Chobby/Chobby#454]
With later engine versions (e.g. 104.0.1-964-g0e56068 maintenance) automatic downloads are not working in Chobby. However, with 104.0.1-287-gf7b0fcc (as currently applied for Zero-K) things are runnning smoothly. The bad thing is, that 104.0.1-287-gf7b0fcc is not available online and thus I assume also not downloadable by the spring-launcher.

**Comment by gajop** [comment]
Are you on windows? Can you replicate this issue by using one of the links here: https://github.com/Spring-Chobby/DistCfg ?

**Comment by gajop** [comment]
Are they working now? I thought the issue was resolved, but @ForbodingAngel reported some problems with newest engine... http://logs.springrts.com/logfiles/65/

**Comment by azaremoth** [comment]
Yes. They are working now! :-)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.05.19, 13:04, Gajo Petrovic <notifications@github.com> schrieb:
Are they working now? I thought the issue was resolved, but @ForbodingAngel reported some problems with newest engine... http://logs.springrts.com/logfiles/65/

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Spring-Chobby/Chobby","title":"Spring-Chobby/Chobby","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Spring-Chobby/Chobby"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gajop in #454: Are they working now? I thought the issue was resolved, but @ForbodingAngel reported some problems with newest engine... http://logs.springrts.com/logfiles/65/"}],"action":{"name":"View Issue","url":"https://github.com/Spring-Chobby/Chobby/issues/454#issuecomment-489060142"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Spring-Chobby/Chobby/issues/454#issuecomment-489060142",
"url": "https://github.com/Spring-Chobby/Chobby/issues/454#issuecomment-489060142",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ForbodingAngel** [comment]
Downloads seem to be working with 1208

**Comment by gajop** [comment]
Thanks!
