### ISSUE TITLE
uninstall leaves files present

### ISSUE THREAD

**Issue by silentwings** [Spring-Chobby/Chobby#457]
all of them!

**Comment by gajop** [comment]
I assume this is about https://github.com/gajop/spring-launcher , are the launcher files deleted at least?
Not sure if I should be deleting all of Chobby... Some important files (e.g. dev mods) could be lost!

**Comment by silentwings** [comment]
I'm not sure which is which but, as far as I could tell, the whole content of C:\Users\***\AppData\Roaming\Chobby remained after uninstalling (using a Win10 uninstall via programs & features menu)

Imo its a good idea if games/maps/etc and other data files did stay in place.

**Comment by gajop** [comment]
Reposted in appropriated repo, closing.
