### ISSUE TITLE
Report and monitor Chili RTT bug

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#46]
Chili Render To Texture can cause bugs with unresponsive controls. This has been disabled to remove the confusion during other development. Ideally RTT would be fixed upstream and reenabled. https://github.com/Spring-Chobby/Chobby

To reproduce:
- Create a list_window which has a scrollbar.
- Scroll to the bottom of the list.
- Modify the children of an item near the top of the list. One that is not visible.
- Scroll back up the list and notice that the modification has not visibly taken effect.
  The modified child will now be unresponsive. The visuals of the window are stuck on one state. Buttons are still clickable.

**Comment by gajop** [comment]
I'm bumping this up to mandatory as it's a critical performance fix.

**Comment by GoogleFrog** [comment]
I have not noticed performance problems. What was the case where performance was a problem?

**Comment by gajop** [comment]
I don't think we'll hit low FPS with our machines but we should aim for as smooth experience as possible, and fixing RTT is probably one of the easiest things we could do.
With RTT enabled I have about 10x more FPS than without it.
