### ISSUE TITLE
chobby fails to display spring when loading (windows 10)

### ISSUE THREAD

**Issue by silentwings** [Spring-Chobby/Chobby#460]
the bug: when clicking start, spring plays its usual chobby music but no window with chobby in displays.

this happens after i have a lua error, which causes me to click the [x] in the top right to close the spring window containing chobby.

the issue then persists through both chobby & windows restarts

i can "fix" the issue by deleting the springsettings.cfg file within in base chobby dir (although it can then re-occur)

**Comment by gajop** [comment]
I think this can be closed now.
