### ISSUE TITLE
'sp' compat flag

### ISSUE THREAD

**Issue by silentwings** [Spring-Chobby/Chobby#462]
Chobby doesn't send the 'sp' compat flag, which tells the server that the client plans to use a scriptPassword, but Chobby seems to semi-ready for this within the code. (Am I missing something here?)

**Comment by silentwings** [comment]
From looking at #465: Chobby isn't sending script passwords (in JOINBATTLE)

**Comment by silentwings** [comment]
possibly rel https://github.com/beyond-all-reason/BYAR-Chobby/issues/1

**Comment by MasterBel2** [comment]
If I understand correctly, this isn't a bug so much as missing functionality, where the missing functionality is "Chobby doesn't send script passwords".

Additional information seems to be that Chobby has somewhat implemented capability (if so, would nice to see a pointer where?)

**Comment by silentwings** [comment]
https://github.com/Spring-Chobby/Chobby/search?q=scriptpassword&unscoped_q=scriptpassword
