### ISSUE TITLE
Mutators should be able to choose the skin used

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#478]
I grepped the mutator and couldn't find "evolved" anywhere, so it must be elsewhere. Setting should be move mutatorside.

**Comment by gajop** [comment]
Go ahead and override https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/widgets/chili/themes/theme.lua in the mutator.

Basically make a copy of it in the same path and change theme.name to what you'd like.
You can also make a copy of the skin and customize it as you'd like, but then you're responsible for maintaining it...
