### ISSUE TITLE
Move the cursed and taprime into a mutator repo

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#484]
@azaremoth @MaDDoXbr 

Please move the two game configs into a mutator repo, like it's done for [Evo](https://github.com/EvolutionRTS/EvoRTS-Chobby) and [BYAR](https://github.com/beyond-all-reason/BYAR-Chobby)

After creating the repo, please install that spring-launcher [GitHub app](https://github.com/apps/springrts-launcher).

The goal of this is to increase the freedom each game developers would have (e.g. with mutators you can put arbitrary widgets without concern for how it might impact other people), while also reducing repository size.

Let me know if you have any questions or need assistance with this.

**Comment by azaremoth** [comment]
@gajo: Great setup. This will facilitate a lot on things including updates and also overwriting the campaign. 

I did place the configs here: https://github.com/azaremoth/cursed-chobby and the Spring launcher app was already in place.

**Comment by gajop** [comment]
@azaremoth thanks! I've removed tc config from this repo now.

@MaDDoXbr Waiting for you now ;)

**Comment by MaDDoXbr** [comment]
@gajop correct me if I’m wrong, but last time we chatted I needed to add rapid to the main game repo before the loader could work - and we’re not quite there yet. Will @azaremoth modification change anything on that front?

**Comment by gajop** [comment]
This particular issue is about moving game configs to a mutator which is unrelated to the issue you were having with distribution. 
That said, it would help of you made this mutator repo, both for the organization and cleanup of this one, as well as for adding independence on your side.

**Comment by MasterBel2** [comment]
@gajop @MaDDoXbr iirc TAPrime has been moved and this issue can be closed?

**Comment by MaDDoXbr** [comment]
Correct @MasterBel2, it can be closed already. Thanks!
