### ISSUE TITLE
Javascript error Lobby crash takes game with it

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#486]
http://logs.springrts.com/logfiles/76/

**Comment by Anarchid** [comment]
What javascript error? The provided log runs for 4500 frames, then results in engine crash with nothing JS-related preceding that anywhere near:
```
670 | [2019-08-22 18:57:23.726] [info] [f=0004500] Metal income has increased!
-- | --
671 | [2019-08-22 18:58:57.912] [error] Spring failed with code: 3221226505
```
The only thing that look like JS errors are ENOENTs when attempting to find a pem file, followed by repeated failures to redownload and verify, before the game is even launched.

**Comment by ForbodingAngel** [comment]
https://i.imgur.com/aQ45sXG.png

https://i.imgur.com/qFM1Ucm.png

**Comment by ForbodingAngel** [comment]
I had assumed the log would contain that information. Apparently I was wrong.

**Comment by gajop** [comment]
I'm not convinced your analysis of the error is correct. What's probably happening is a *spring* crash causing this popup to appear from the launcher.

The launcher has not crashed.
I've made an issue on the launcher side to avoid creating unnecessary popups: https://github.com/gajop/spring-launcher/issues/21
