### ISSUE TITLE
Wishlist for BAR + Chobby & Bugs / weird problems

### ISSUE THREAD

**Issue by icexuick** [Spring-Chobby/Chobby#494]
So, for BAR we've tried to implement Chobby, which has some nice advantages over SpringLobby. Of course, i looks, nice, but also the install (for the ones who do actually can install it) is slick and smooth.

However we've come across quite a few problems, some small, but most are pretty fundamental. Here's a list of the top things we would like/need to definitively use Chobby.

Major issues first:

- The **install procedure** is fixed to "my documents", which has resulted in many players not able to install it at all (locked/secured folder or network folder). You should be able to choose your own install location 
- **Updating/Unpacking issues** where (new) engine/game updates don't unpack right - resulting in errors and not able to play (only gets partially unpacked - all .exe's are missing f.e.)
- You cannot host your own game - you need to join BAR servers. 
- **Friends** don't seem to work that well - i have had many strange encounters were friends don't show up or friend requests sometimes don't work - also offline friends don't show up.
- **Fonts** aren't always sharp or positioned well - we already did some upgrades but still it's not always as crisp, as say SpringLobby.
- **Starting positions** is completely missing, as well as start boxes. (fixed, starting boxes, choose ingame, etc.)
- You can't set your **Team color(s)**
- **Replays** aren't working - but this could be just a minor configuration issue
- We need to make **custom map-thumbnails** for each map manually - Seems that Chobby doesn't use/read the maps own thumbnail.
- Some menu's (layout) work a bit funky with smaller screens or larger (wide)screens
- We'd like **tooltips for each setting** (currently only checkboxes)
- **Download Maps** doesn't seem to work correctly

We've fixed quite some issues we had ourselves. Check the BAR & Chobby Issue list we keep on our Trello board here: https://trello.com/c/rYuDxDvj/262-current-issues

For now - we need to use Spring Lobby.
Mainly because of the following things: it's install-able and working for like 95+% of the current people, but also for hosting our own games, get the right updates, set our starting positions, have a pretty decent working friends/chat system, see all maps we play, choosing colors and watch replays.

Some also prefer the easier way of using Springlobby as an active 'background'-app, which also is just a 'window'. Chobby can be a window, but when you play, you want to go fullscreen and afaik you can't separate those two.

**Comment by gajop** [comment]
I've made some issues and linked to existing ones. Some of the stuff you mentioned is already fixed. Most bugs need way more info in order to be fixed.

https://github.com/gajop/spring-launcher/issues/18

https://github.com/Spring-Chobby/Chobby/issues/418
https://github.com/Spring-Chobby/Chobby/issues/495
https://github.com/Spring-Chobby/Chobby/issues/249
https://github.com/Spring-Chobby/Chobby/issues/73
https://github.com/Spring-Chobby/Chobby/issues/322
https://github.com/Spring-Chobby/Chobby/issues/496
https://github.com/Spring-Chobby/Chobby/issues/497
