### ISSUE TITLE
Chobby errors out on start (Unsupported Protocol?)

### ISSUE THREAD

**Issue by ForbodingAngel** [Spring-Chobby/Chobby#498]
http://logs.springrts.com/logfiles/127/

**Comment by gajop** [comment]
This seems to be either a spring-launcher (https://github.com/gajop/spring-launcher/issues) or pr-downloader (https://github.com/spring/pr-downloader) issue. Are you using the newest version of spring-launcher? The portable version won't autoupdate for you.

**Comment by gajop** [comment]
In fact, latest EvoRTS seems to be version: 1.59.0, so I'm closing this issue as being due to using an outdated version of the launcher

**Comment by ForbodingAngel** [comment]
How do I manually update it? And how do I know when to update it? You've buried the lede here.

**Comment by gajop** [comment]
With the portable version updating the launcher becomes entirely your responsibility (which is probably good if you want to use a 3rd party distribution system like Steam).

This means that whenever you make a new version (which happens when you modify something in dist_cfg), you need to download and install a new version from the links I gave you previously.

**Comment by ForbodingAngel** [comment]
I'm fine with updating it myself, but I don't know what files to update. Can you point me to the files that need to be updated?

**Comment by gajop** [comment]
@ForbodingAngel You just need to get the new executable

**Comment by ForbodingAngel** [comment]
Updating the executable resulted in the same issue:
http://logs.springrts.com/logfiles/133/

**Comment by ForbodingAngel** [comment]
To further clarify, I downloaded the newest build via this link:
https://spring-launcher.ams3.digitaloceanspaces.com/EvolutionRTS/EvoRTS-Chobby/Evolution%20RTS-portable.exe

Which is where you said it would be here:
https://i.imgur.com/SrVVrmy.png

I didn't hash old vs new, but I did make note that there was about .5MB filesize difference between the two (although this is windows reporting filesize, so far from an exact value).

**Comment by gajop** [comment]
The version seems correct:
log:
`[2020-01-20 03:31:00.619] [info] Evolution-RTS - 1.59.0`

latest (https://spring-launcher.ams3.digitaloceanspaces.com/EvolutionRTS/EvoRTS-Chobby/latest.yml) :
`version: 1.59.0`

However I can't seem to download the engine, even if I try using the standalone pr-downloader:
```
(base) ➜  ~ ~/opt/spring/bin/pr-downloader --download-engine "104.0.1-1344-g07bdbaf maintenance"
pr-downloader 0.7-496-g813ac02
[Info] ../tools/pr-downloader/src/FileSystem/FileSystem.cpp:194:setWritePath():Using filesystem-writepath: /home/gajop/.spring
[Info] ../tools/pr-downloader/src/pr-downloader.cpp:173:DownloadSetConfig():Free disk space: 211020 MB
[Info] ../tools/pr-downloader/src/Downloader/CurlWrapper.cpp:51:DumpVersion():libcurl 7.58.0 OpenSSL/1.1.1
[Error] ../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:580:download():No mirrors found
[Error] ../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:580:download():No mirrors found
[Info] ../tools/pr-downloader/src/FileSystem/FileSystem.cpp:596:extract():Extracting /home/gajop/.spring/engine/spring_{maintenance}104.0.1-1344-g07bdbaf_minimal-portable-linux64-static.7z to /home/gajop/.spring/engine/104.0.1-1344-g07bdbaf maintenance
[Error] ../tools/pr-downloader/src/FileSystem/SevenZipArchive.cpp:122:CSevenZipArchive():Error opening /home/gajop/.spring/engine/spring_{maintenance}104.0.1-1344-g07bdbaf_minimal-portable-linux64-static.7z No such file or directory
[Error] ../tools/pr-downloader/src/pr-downloader.cpp:59:download_engine():Failed to extract engine 104.0.1-1344-g07bdbaf maintenance
[Error] ../tools/pr-downloader/src/main.cpp:221:main():Error occurred while downloading: 4
```

Sounds to me like you may want to update the engine to one of the available ones: https://springrts.com/dl/buildbot/default/maintenance/

(Also as a WTF sidenote, why are there so few maintenance builds available? I've never seen so few.  Are they being pruned due to age? Any ideas @abma ?)

**Comment by abma** [comment]
> Are they being pruned due to age? Any ideas @abma ?

yep: https://github.com/spring/spring/blob/develop/buildbot/master/cleanup.sh

i guess it should be changed to sth. like that and the last n build kept for the maintenance + develop branch:

https://github.com/spring/pr-downloader/blob/master/scripts/cleanup-builds.py

**Comment by abma** [comment]
-> https://springrts.com/mantis/view.php?id=6361

**Comment by gajop** [comment]
@abma Thanks, appreciated :) We're kinda stuck having to update engine references until 105 comes out

**Comment by ForbodingAngel** [comment]
@gajop But I distribute the engine with the launcher. I don't really understand why the engine not being available on the spring servers should effect the portable launcher when it already has the engine available to it?

**Comment by gajop** [comment]
@ForbodingAngel I suppose the launcher doesn't really know this and tries to download anyway.

Sounds like an issue for https://github.com/gajop/spring-launcher/issues although I'm not sure how to implement that as pr-downloader doesn't seem to have a way for determining what's downloaded

**Comment by ForbodingAngel** [comment]
It doesn't seem out of the question for the _portable_ launcher to assume that the engine is already there, considering that that is the primary use case for the portable launcher anyway. The last thing I want is to be tied to an arbitrary spring build deletion cycle.
