### ISSUE TITLE
Optimize TextBox for multiline display, use a table of strings instead of one big string

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#50]
The current large textbox system creates a lot of string concatenation and rendering.

**Comment by gajop** [comment]
Continuation of https://github.com/Spring-Chobby/Chobby/issues/7

**Comment by gajop** [comment]
Affected by https://github.com/Spring-Chobby/Chobby/commit/14a09c88eaf819af33f2ae651fc201e4142da5c3
Slower rendering (with no RTT) but doesn't do concatenation at least.
