### ISSUE TITLE
move springsettings.lua inside the gameconfig?

### ISSUE THREAD

**Issue by Ruwetuin** [Spring-Chobby/Chobby#502]
The following line has been hardcoded:
https://github.com/Spring-Chobby/Chobby/blob/master/LuaMenu/widgets/chobby/components/configuration.lua#L243

i'd rather have to load it from somewhere inside the gameConfig like:
self.game_settings = VFS.Include(LUA_DIRNAME.."configs/gameConfig/byar/defaultSettings/springsettings.lua")

**Comment by gajop** [comment]
To use this, you need to add the following lines in your repo's config file:
https://github.com/Spring-Chobby/Chobby/commit/f7f46b08341fbca6c5e1c9e0694323dbc3d1387e#diff-efd27f18c699b3db608ab48caca72e8aR9
&
https://github.com/Spring-Chobby/Chobby/commit/f7f46b08341fbca6c5e1c9e0694323dbc3d1387e#diff-efd27f18c699b3db608ab48caca72e8aR38

You can then add the file in the location you desire.
Hopefully this works for you - let me know if I missed anything
