### ISSUE TITLE
chat - arrow keys copying last message 

### ISSUE THREAD

**Issue by PtaQQ** [Spring-Chobby/Chobby#504]
Please add the possibility to call the copying of last messages using arrow keys in chat. Not a priority but I assume it won't take much effort. Same as it works in command prompts.

arrow up - copies your last message into the text console 
arrow up again - copies message previous to the above 
etc 
...
arrow down - return to the next message 

Pretty useful and makes it way easier to communicate with bots, as you don't have to retype/manually copy the message if you make a typo in the command.

**Comment by MasterBel2** [comment]
Copy of #250 

Related PR (#513) is currently under review.
