### ISSUE TITLE
Create Settings Screen

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#52]
The settings screen should be in a tab on the right panel. It should include settings for ingame and settings for the lobby.  These settings will need to be stored in a config and applied either just before Spring.Start or when the lobby is closed (to make the lobby have the right settings next time).

**Comment by GoogleFrog** [comment]
This milestone is here because Chobby needs to be able to be windowed and launch fullscreen spring.

**Comment by gajop** [comment]
Settings are probably important and going to happen before all the required engine changes anyway.
That aside, did you try setting it in overlay (https://github.com/Spring-Chobby/Chobby/blob/master/LuaUI/widgets/gui_standalone_lobby.lua#L15)? That's pretty useful if we want lobby-specific overrides, although it doesn't always work and there isn't a list of what works/doesn't work as far as I know.

**Comment by GoogleFrog** [comment]
Fullscreen, WindowBorderless, WindowPosX and WindowPosY do not work as overlays.

Upon exiting Spring the values of Fullscreen, WindowPosX and WindowPosY are overridden by the state of Spring. It seems to be impossible to set these values in Springsettings.cfg such that they persist after Spring is closed. Launching subprocesses with these changed values works.

I was hoping to implement a fullscreen toggle for the lobby but it looks impossible at the moment. Not even if we prompt the user to restart for the setting to take effect.

**Comment by gajop** [comment]
It seems that there are UI commands for this (https://springrts.com/wiki/UI_commands).
Spring.SendCommands("fullscreen") for toggling and it might be able to send numbers to force specific states (docs say nothing about it).

While not really important to Chobby, I think this is the same case with shadows. Setting the config value doesn't work, but the UI command does.

**Comment by GoogleFrog** [comment]
Thanks, this should be enough for me to get something working. You won't be able to go between all states without a restart but it should be sufficient for basic functionality.

**Comment by GoogleFrog** [comment]
I still have trouble switching to WindowedFullscreen because any values I set for WindowPosX and WindowPosY are overridden upon closing Spring.

**Comment by gajop** [comment]
It sounds like it might require engine changes. Best to make a separate issue for that in that case.

**Comment by GoogleFrog** [comment]
A basic settings screen is in. The next step is to think about which settings we want and to make a generic way to add settings.

**Comment by GoogleFrog** [comment]
Probably counts as complete. Extra tickets will be opened for extra things.
