### ISSUE TITLE
pr-downloader API fails to download more than one archive

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#54]
Complains about files being already open, etc.

**Comment by abma** [comment]
improper usage of the api? in springlobby it works fine?

**Comment by gajop** [comment]
That would be fairly unlikely, took me a while to debug this.
It seems that downloads wasn't being cleared between searches, meaning that it would keep old ids. 

And if you repeat downloads you will have have something akin to "{1, 1, 1, 1}" in the downloads list. It will open the first one (successfully) and fail when trying to open the second one (since it's the same file and already open).

**Comment by gajop** [comment]
This is basically key part of the fix: https://github.com/spring/pr-downloader/commit/17dd5bf8b8b425276b222b76420a1064dcc7c847#diff-3153702f12a091345c1f9bce8590b6edR137

**Comment by abma** [comment]
this possible introduces a crash / memory corruption :-|

**Comment by gajop** [comment]
Do you want to elaborate how because I don't see it?

**Comment by abma** [comment]
but ok, lets see, i run this with addresssanitize by default :)

**Comment by abma** [comment]
oh.... it does not. i'm getting old, sorry :-|

(mixed it somehow with "searchres"...)

**Comment by gajop** [comment]
Hey I'm just glad it works.
PS: May also want to add it in DownloadShutdown or other places where IDownloader::freeResult(searchres); is invoked.

Seeing as how these two things are related, maybe it should be passed to IDownloader::freeResult as a second parameter and let it handle it (and thus enforce it's always cleared)
