### ISSUE TITLE
Spring Subprocess tracking - basic functionality

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#60]
We need to be able to know whether the started Spring subprocess has terminated or not.
A simple Spring.IsSubProcessAlive(subprocessPID) -> boolean isAlive, where subprocessPID is only valid if it's a previously started (from this instance) Spring subprocess

**Comment by GoogleFrog** [comment]
I'm bumping this up a milestone because chobby needs this to send ingame status and recover nicely after game crashes.

**Comment by gajop** [comment]
luamenu route we took doesn't require this anymore
