### ISSUE TITLE
Fix the current mainmenu->subtree navigation confusion

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#69]
It has a number of issues:
~~1) There's no indication of where in menu tree you are. This should be done by introducing breadcrumbs or a fully visible tree (e.g. by using Content Place for the subtree like how Dota2/LoL do it). Breadcrumbs might not be clear and also too wide.~~
~~2) Exit button should be far away from other buttons, probably all the way in the bottom, so people don't press it accidentally.~~
3) Buttons should use fixed size, especially height (https://github.com/Spring-Chobby/Chobby/issues/68)
4) There is no indication to the user what button explores the subtree and what does something else, like open something in the Concent Place

I think it's key to get the basic interface going very early in the project.

**Comment by GoogleFrog** [comment]
How do you indicate that the main menu is a tree and all the submenus are tabs?

**Comment by gajop** [comment]
Well I still think that the tree structure is unnecessary, but I would differentiate the two by using different button image and/or color.

**Comment by gajop** [comment]
I think this is much better now. In the future we will probably want to resize some elements and make icons out of the others, but specific issues can be opened for that.
