### ISSUE TITLE
Allow Chili skins to be loaded from specific folder

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#72]
This should allow us to create skins outside of the Chili folder and make it easier to use the library while keeping all project-specific stuff out of the library folder.
It shouldn't be too hard to do, but requires some internal Chili knowledge.
Here are how some example functions could look like:
SkinUtils:AddSkinFolder(folderPath)
SkinUtils:RemoveSkinFolder(folderPath)

**Comment by gajop** [comment]
It seems you can only have one skin folder and have to copy everything from existing chili into it?
I think it should use something like the API above, which would allow it to have custom skin folders in addition to the default one. 

I also don't think we should ever modify the api_chili.lua file and move the entirety of chili into a library. Just like liblobby and other things, overrides should happen outside of the libs folder so everything is mergable upstream.

**Comment by GoogleFrog** [comment]
From what I could tell you already modified api_chili in a similar way. The line does not occur in the redundant api_chili: https://github.com/Spring-Chobby/Chobby/commit/d25d955ed672453f87806a0f2779b0820c87e663#diff-04aae8db4e766a7d655e50295f5449a4R34

Our method of including chili as a library is already bad so I was not violating any nice properties.

**Comment by gajop** [comment]
Yep, that line existed because of how the chili dir was specified. It should no longer be necessary with the way we're including libraries now (although chili still has to be converted which i didn't yet because i don't know what jk thinks).

This is unrelated to the skinning though! Even if you made a single, global, skin folder it would much be better suited to a config file instead. Ideally we'd want to supply a list of additional skin folders, instead of overriding the existing one
