### ISSUE TITLE
Weird recursion(?) causing OOM

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#76]
Happens sometimes, last one just happened as I launched Chobby

[f=-000001] Fatal: LuaUI: cannot allocate more memory! (805307079 bytes already used, 805306368 bytes maximum)
[f=-000001] Fatal: LuaUI: cannot allocate more memory! (805307079 bytes already used, 805306368 bytes maximum)
[f=-000001] Fatal: LuaUI: cannot allocate more memory! (805307079 bytes already used, 805306368 bytes maximum)
[f=-000001] Fatal: LuaUI: cannot allocate more memory! (805307079 bytes already used, 805306368 bytes maximum)
[f=-000001] Error: LuaUI::RunCallIn: error = 4, Update, [Internal Lua error: Call failure] not enough memory

**Comment by GoogleFrog** [comment]
Added the GC widget https://github.com/Spring-Chobby/Chobby/commit/1316586430714d3cdfa0eb8d44e510a75266667d

It will be useful to see if it goes away. Pay attention and report it if it occurs.

**Comment by gajop** [comment]
Cannot reproduce anymore.
