### ISSUE TITLE
Main window too wide after going from one-panel mode to two-panel mode in settings

### ISSUE THREAD

**Issue by KingRaptor** [Spring-Chobby/Chobby#78]
I'm having an intermittent issue where after choosing Always One panel in settings, then Autodetect or Always Two, the Main Window is resized such that its right edge meets the right edge of the screen. 
This is fixed by going to the Custom Battle sections in either SP or MP and then clicking Back.

**Comment by GoogleFrog** [comment]
Fixed https://github.com/Spring-Chobby/Chobby/commit/06b6679da85019cb85aa5270bfcfb5e436433da0
