### ISSUE TITLE
No progressbar background on Windows

### ISSUE THREAD

**Issue by gajop** [Spring-Chobby/Chobby#80]
[f=0016835] Warning: Couldn't find texture "libs/chiliui/luaui/chili/chili/skins/robocracy/tech_progressbar_empty.png"!
[f=0016835] Warning: Couldn't find texture "libs/chiliui/luaui/chili/chili/skins/robocracy/tech_progressbar_full.png"!

**Comment by GoogleFrog** [comment]
I've been working with progress bars for a while and they are definitely visible. Reopen if we get another report.
