### ISSUE TITLE
Add socket.http to engine

### ISSUE THREAD

**Issue by Anarchid** [Spring-Chobby/Chobby#90]
- It is possible to download files over http with naked luasocket, but that's reinventing the wheel
- security wise, socket.http isn't any safer than naked socket (because of the above) so there's no reason to keep it disabled
- need to figure out how it was removed and unremove it

**Comment by abma** [comment]
> need to figure out how it was removed and unremove it

it was never added ;-)

**Comment by abma** [comment]
as you may ask why it wasn't added:

- doesn't support https
- doesn't support proxy
- the scripts can be added when needed to the game
- if i remember right: socket.http was blocking and has to be modified to be useful for spring
- it is large

-> it should be added to the game/module where needed (its lua only!)

**Comment by gajop** [comment]
the pr-downloader solution sounds better in that case

**Comment by gajop** [comment]
This will probably never happen.
