### ISSUE TITLE
Unresizable window

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-Chobby/Chobby#93]
If you start the game in windowed fullscreen and then set the lobby to windowed the window is not resizable.

**Comment by gajop** [comment]
This might be a Spring or Windows-only issue. I can't seem to reproduce on Linux.

**Comment by GoogleFrog** [comment]
Fixed in engine. Probably this? https://github.com/spring/spring/commit/509d10f9d919783659dfcb9706725eb26c323db5

**Comment by ashdnazg** [comment]
indeed
